### ISSUE TITLE
Sorting Exceptions

### ISSUE THREAD

**Issue by raphcho** [bugsnag/bugsnag-android#1]
It is possible to add some filters to group exceptions not by phone and exception but only by exceptions?

**Comment by wangdaliu** [comment]
@loopj 
Group globally
Groups by the exception type, no matter where in your code the exception happened

hey,  i want to know how to use this way to group in android code
Thanks!

**Comment by jessicard** [comment]
@wangdaliu Pulling from what @loopj said - you can go to the Project Settings page on your Bugsnag dashboard, and add the exception classes to the Error Grouping Settings to choose how to group your exceptions:

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3130343030392f31373538362f64653763663832652d343837652d313165322d386238352d6337653165663337333034642e706e67](https://cloud.githubusercontent.com/assets/621904/6472496/d144c606-c1a7-11e4-8bbf-2ecc8958403e.png)

Thanks!
