### ISSUE TITLE
Attempting to perform JNI actions synchronously during a signal handler is not safe

### ISSUE THREAD

**Issue by allight** [bugsnag/bugsnag-android#1026]
### Describe the bug

The code here: https://github.com/bugsnag/bugsnag-android/blob/ff3c8b66c08dfe1f68360b22b67613137be00e8b/bugsnag-plugin-android-anr/src/main/jni/anr_handler.c#L48-L62 violates JNI invariants and is not safe.

During handling of SIGQUIT signals your library can attempt to call JNI functions directly on the current thread. Safe use of JNI code requires that the thread it is called on is in the native thread state. This can only be accomplished by either (1) the (previously unattached) thread calling the AttachCurrentThread method or (2) the most recent java language function call being a native method (and control having been passed to the native method implementation). Performing JNI calls with the thread in an incorrect state can cause many issues including SEGV crashes as the GC or stack-tracing attempts to walk an invalid stack.

Depending on the requirements of bugsnag there are a few ways you could solve this. The easiest would be to simply have a single signal-handling thread that the signal-handler wakes up with a semaphore. Note that this handling cannot be synchronous because waiting for the handling to finish before allowing the signal-handler to continue could cause deadlocks, depending on where the runtime was during the signal.

As another more minor issue this entirely disables the ART internal SIGQUIT/ANR dumping system since it relies on a [signal-catcher thread](https://cs.android.com/android/platform/superproject/+/master:art/runtime/signal_catcher.cc;l=171;bpv=0;bpt=1) being [woken up by sigwait](https://cs.android.com/android/platform/superproject/+/master:art/runtime/signal_set.h;drc=master;bpv=0;bpt=1;l=46) which your unblocking of the SIGQUIT mask will break. Leaving this as just an FYI though since I'm not sure if this is intentional or not.

### Environment
* Android version: All
* Bugsnag version: Unknown
* Emulator or physical device: All

**Comment by yousif-bugsnag** [comment]
Hi @allight,

Thanks for the detailed report. We are investigating this and will update you as soon as we know more.

**Comment by phillipsam** [comment]
A fix for this has now been released in [v5.5.1](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.5.1).
