### ISSUE TITLE
Unit Test configuration

### ISSUE THREAD

**Issue by sdoward** [bugsnag/bugsnag-android#103]
Is there a recognised way to stop Bugsnag reporting errors in unit tests? It would be nice if we could switch error reporting off. As a work around I do the following...

```java
Bugsnag.init(mock(Context.class), ""); //mock Context with Mockito and pass in an empty string as the API_Key
Bugsnag.beforeNotify(new BeforeNotify() { //assign a BeforeNotify which halts reporting of all exceptions
    @Override
    public boolean run(Error error) {
        return false;
    }
});
```

I had to create a custom TestRunner to make sure this is called on each test.

**Comment by hzsweers** [comment]
test

**Comment by ndurell** [comment]
We put a thin wrapper around bugsnag this way we can pass it in as a dependency and mock the whole thing during unit tests.

**Comment by snmaynard** [comment]
You could mock like @ndurell mentions or use a combination of [setReleaseStage](https://github.com/bugsnag/bugsnag-android#setreleasestage) and [setNotifyReleaseStages](https://github.com/bugsnag/bugsnag-android#setnotifyreleasestages) when running tests.

```java
Bugsnag.setNotifyReleaseStages("production", "development");
Bugsnag.setReleaseStage("testing");
```
