### ISSUE TITLE
ANR reports missing custom global metadata

### ISSUE THREAD

**Issue by pbajurko** [bugsnag/bugsnag-android#1068]
### Describe the bug
Not sure if it is a bug or feature request, but it would be useful if we get same custom metadata tabs for ANR as we get for crashes

* Bugsnag version:
5.3.1

**Comment by mattdyoung** [comment]
Hi @pbajurko 

Thanks for reporting this. It looks like custom global metadata is mistakenly not being included in ANR reports so we'll aim to fix in a future release.

**Comment by mattdyoung** [comment]
Fixed in [v5.6.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.6.0)
