### ISSUE TITLE
Why are consumer ProGuard rules included?

### ISSUE THREAD

**Issue by JakeWharton** [bugsnag/bugsnag-android#107]
As far as I can tell none of them are needed. This library has no reflection so both obfuscation and stripping will behave correctly without them.

Currently it disables both obfuscation and stripping without a clear reason as to why.

**Comment by JakeWharton** [comment]
From the history it looks like these rules were once used to ProGuard the release jar and erroneously were converted to consumer rules?

Unless someone sees something that I don't, these should be removed to allow obfuscation and unused code stripping.

**Comment by JakeWharton** [comment]
Having manually removed the embedded proguard rules, everything still works fine and allowed 77 methods to be removed as well as obfuscation to occur.

I'm sending a PR.

**Comment by kattrali** [comment]
They were used at one point, but that has long since passed. Merging.
