### ISSUE TITLE
Not able to update to version 5.5.1

### ISSUE THREAD

**Issue by guilherme-pereira-ifood** [bugsnag/bugsnag-android#1087]
### Describe the bug
Just tried to update to Bugsnag 5.5.1 and received this error:

```
Could not determine the dependencies of task ':app:compileBrazilDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:brazilDebugCompileClasspath'.
   > Could not find com.bugsnag:bugsnag-android-core:5.5.1.
     Required by:
         project :app > com.bugsnag:bugsnag-android:5.5.1
   > Could not find com.bugsnag:bugsnag-plugin-android-anr:5.5.1.
     Required by:
         project :app > com.bugsnag:bugsnag-android:5.5.1
   > Could not find com.bugsnag:bugsnag-plugin-android-ndk:5.5.1.
     Required by:
         project :app > com.bugsnag:bugsnag-android:5.5.1

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Checking the maven repository, 5.5.1 version of [bugsnag anr](https://mvnrepository.com/artifact/com.bugsnag/bugsnag-plugin-android-anr) and [bugsnag ndk](https://mvnrepository.com/artifact/com.bugsnag/bugsnag-android-ndk) does not exists.

Version 5.5.0 is working just fine.

### Steps to reproduce
Just update Bugsnag to 5.5.1 on Gradle: `com.bugsnag:bugsnag-android:5.5.1` and try to build the project (`./gradlew app:assembleDebug`).

**Comment by benkyllo** [comment]
Both 5.5.1 and 5.5.0 not working for me, but 5.4.0 is.  Seeing the same could not find error.

**Comment by johnkiely1** [comment]
Hi @guilherme-pereira-ifood
 
We believe this was an intermittent issue that had been caused by some downtime at Sonatype that happened in the middle of our Android publishing process. Since then we have been able to publish successfully so with that the original problem should be resolved. Would you be able try the update again now?

**Comment by guilherme-pereira-ifood** [comment]
Hey @johnkiely1,

Thanks for the help, it's now working 👍
