### ISSUE TITLE
Using Configuration without <metadata> field in Manifest causes crash 

### ISSUE THREAD

**Issue by ElviraBurchik** [bugsnag/bugsnag-android#1128]
Hello! I hope somebody could answer my question 👋

I'm trying to initialize Bugsnag with API key and app version without using Android Manifest via Configuration object. 

Documentation says:
> Configuration.load uses your app manifest to set initial configuration values, allowing you to augment and override the values before they are used to start Bugsnag. You can use the Configuration constructor to avoid using the manifest file.

So I assumed that I can escape modifying Manifest. However, I get crash: `Bugsnag is unable to read config from manifest.`

As I can see [from this piece](https://github.com/bugsnag/bugsnag-android/blob/cbd6c9f922c0300dec6ed702a63e40adcce824c5/bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt#L48), SDK tries to read manifest and get metadata even with user-provided API key. I don't have `<metadata>` field in manifest, so I get the crash. 

My question is: is there any way to run Bugsnag without `<metadata>` in manifest or there is no way to escape it? 

P.S.: I checked iOS as well: [it also checks `info.plist` for `bugsnag` key](https://github.com/bugsnag/bugsnag-cocoa/blob/master/Bugsnag/Configuration/BSGConfigurationBuilder.m#L17), but can go on with API key = nil.

**Comment by phillipsam** [comment]
Hi @ElviraBurchik ! 

You can avoid using the `AndroidManifest` by using the [Configuration constructor](https://github.com/bugsnag/bugsnag-android/blob/afa2da681a0678c3805b0a80dc7458e5157be52a/bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java#L30) (instead of using `Configuration.load`) to load your API key. This would look something like this:

```
val config = Configuration (apiKey)
Bugsnag.start(this, config)
```

Let us know how you get on!

**Comment by ElviraBurchik** [comment]
Hi @phillipsam!

That's what I need, thank you answer 😊
