### ISSUE TITLE
Error: 'com.bugsnag.android.BugsnagReactNativePlugin' is not on the classpath

### ISSUE THREAD

**Issue by ElviraBurchik** [bugsnag/bugsnag-android#1131]
Hi 👋 

I work on React Native package to wrap up Bugsnag initialization with correct parameters at @shopify. Could somebody help with an issue I get?

When I run Android app, I get crash with: 
`Bugsnag : Plugin 'com.bugsnag.android.BugsnagReactNativePlugin' is not on the classpath - functionality will not be enabled.`

I searched the plugin file in my system, and it feels like it's somehow missing. 

I'd appreciate any tips on fixing it 🙏

**Comment by phillipsam** [comment]
Hi @ElviraBurchik - can you please write into support@bugsnag.com and give us some details of your project structure? 🙏

**Comment by ElviraBurchik** [comment]
Sure, @phillipsam
