### ISSUE TITLE
 jumnajl

### ISSUE THREAD

**Issue by koolfreak** [bugsnag/bugsnag-android#1141]
Please checkout our [documentation](https://docs.bugsnag.com/platforms/android/) for guides, references and tutorials.

If you have questions about your integration please contact us at [support@bugsnag.com](mailto:support@bugsnag.com).

Alternatively, view additional options at [support.md](../SUPPORT.md).

**Comment by xander-jones** [comment]
👋. Hey, I assume this was raised in error, but let us know if you're encountering an issue.

**Comment by koolfreak** [comment]
sorry my son has autism and type down accidentally. 
But i have a question, does bugsnag log exception even if the app is in background?

**Comment by xander-jones** [comment]
So long as the App processes is running, Bugsnag will report events. Note that there's an `app.inForeground` flag and `app.durationInForeground` on each report that will tell you whether the error happened in foreground or not.

![Screenshot 2021-02-16 at 13 51 25](https://user-images.githubusercontent.com/9535852/108071884-267e9a00-705e-11eb-87d9-7f7e7d96f29b.png)

**Comment by koolfreak** [comment]
@xander-jones thanks
