### ISSUE TITLE
Recommend using fixed version when specifying dependency

### ISSUE THREAD

**Issue by efung** [bugsnag/bugsnag-android#115]
On the documentation page here:

https://docs.bugsnag.com/platforms/android/#installation

the line suggested to add to dependencies says:

```
compile 'com.bugsnag:bugsnag-android:3.+'
```

Specifying dynamic versions introduces non-determinism to a build. There is a good [blog post](http://blog.danlew.net/2015/09/09/dont-use-dynamic-versions-for-your-dependencies/) about this.

I would suggest keeping this page updated (automatically) with the version number of the current stable release of the SDK.

**Comment by kattrali** [comment]
Thank you for the report, @efung. The documentation has been updated.
