### ISSUE TITLE
Initializing client: in main activity and/or in Application subclass?

### ISSUE THREAD

**Issue by efung** [bugsnag/bugsnag-android#116]
In the [installation docs](https://docs.bugsnag.com/platforms/android/#installation) the suggestion is to initialize the Bugsnag client in your `Application` subclass.

However, in the integration guide, which is shown right after creating a new Bugsnag project, the documentation there says to add it in your app's main activity's `onCreate`.

Please clarify the documentation so that these two pages are consistent.

**Comment by kattrali** [comment]
Thank you for the report, @efung. The client should be initialized in the application subclass’ `onCreate` method. The documentation will be updated shortly.

**Comment by redochka** [comment]
What happens when I publish a new version of my app after adding bugsnag library for the first time? When Android auto updates the app, my main activity won't be launched necessarily. So Bugsnag.init() will never run.

**Comment by redochka** [comment]
Sorry i found the answer. Bugsnag init can be in onCreate() method of my main App class (the one referenced in the <application android:name="xxx"
