### ISSUE TITLE
libbugsnag-ndk.so addBreadcrumb crashes the app with SIGABRT

### ISSUE THREAD

**Issue by troy-lamerton** [bugsnag/bugsnag-android#1187]
### Describe the bug

In production we're seeing this crash reported for multiple users:

```log
SIGABRT Abort program 
    libbugsnag-ndk.so:181211 bsg_populate_jni_cache
    libbugsnag-ndk.so:182573 bsg_populate_crumb_metadata
    libbugsnag-ndk.so:176645 Java_com_bugsnag_android_ndk_NativeBridge_addBreadcrumb
```

It is the 3rd most common error reported for our project at the moment.
So far it has only been reported by the [BlueStacks emulator](https://www.bluestacks.com/). A good percentage of our target market runs BlueStacks to play our game.

In case its helpful, Bugsnag employees can view the events here: https://app.bugsnag.com/the-naughty-cult-ltd/clash-of-streamers-1/errors/6000b0e53d04e700174e0398?filters[event.since][0]=7d&filters[error.status][0]=open&filters[app.release_stage][0]=production

### Environment

We use the bugsnag-unity SDK and build for android.

* Android version: 7.1.1
* Bugsnag version: v4.22.3 (as part of bugsnag-unity v4.8.4)
* Emulator or physical device: BlueStacks emulator

**Comment by xander-jones** [comment]
👋. hey @troy-lamerton, we've recently made some [improvements](https://github.com/bugsnag/bugsnag-unity/pull/214) in this area, that were released in https://github.com/bugsnag/bugsnag-unity/releases/tag/v4.8.5 that I believe should fix the issue you're seeing. Please can you update to this new version and let us know how you get on.

**Comment by troy-lamerton** [comment]
Sounds good. I will reopen if the crash happens again after updating.
