### ISSUE TITLE
Wish for the Documentations

### ISSUE THREAD

**Issue by DreamGamer** [bugsnag/bugsnag-android#1205]
Hello, i'm new to Bugsnag, so a want to learn everything i can do with bugsnag. I tryed to read the Documentations and at some points, i got really confuzed. At some points, it's really hard to find some Informations and for me it's impossible to find some informations like where should i import Configuration see [here](https://docs.bugsnag.com/platforms/android/configuration-options/). I searched with the google search engine and read a lot of the documentations, but i can't find where i should import it. I can't import it from the @bugsnag/react-native package, so now currently i can't use the full bugsnag functionallity.

I'm really sure that bugsnag is really easy to use, but at some points i really stuck, because i don't find enough informations in the documentations.

My Wish for the Documentations is, is it possible, to add full examples? I think, reading full code is a good way to understand how it works and a full working example is easy to integrate in the documentations. 

Best Regrads
DreamGamer

**Comment by DreamGamer** [comment]
Oh, i don't know how, but i just got to the wrong programming lanuage, so the Configuration issue i named above, was my fault, it's a introduction for android, but again with a full example of code i would never had this issue.

**Comment by mattdyoung** [comment]
Hi @DreamGamer 

All of our Bugsnag error reporting libraries have full example projects linked to from our documentation.

For React Native the example projects can be found here:
https://github.com/bugsnag/bugsnag-js/tree/next/examples/reactnative

Our documentation for integrating Bugsnag into a React Native app is here:
https://docs.bugsnag.com/platforms/react-native/react-native/

If you're having any specific issues, please do contact us at support@bugsnag.com with details of what isn't working and we can assist.
