### ISSUE TITLE
Unresolved reference: MetaData

### ISSUE THREAD

**Issue by AndreSand** [bugsnag/bugsnag-android#1234]
Hi, I'm setting up Bugsnag Leak Uploader, but I'm not able to import. I'm following the
tutorial https://square.github.io/leakcanary/recipes/#uploading-to-bugsnag

Error with `import com.bugsnag.android.MetaData`

bugsnag version:
    classpath 'com.bugsnag:bugsnag-android-gradle-plugin:5.+'
    implementation 'com.bugsnag:bugsnag-android:5.+'

**Comment by mattdyoung** [comment]
Hi @AndreSand 

That tutorial wasn't authored by Bugsnag and isn't something we maintain.

It looks like the instructions are based on the legacy bugsnag-android v4.x:
https://docs.bugsnag.com/platforms/android/legacy/

There were some breaking changes in v5.x, but it should be possible to adapt the approach by following our upgrade guide:
https://github.com/bugsnag/bugsnag-android/blob/next/UPGRADING.md#upgrade-from-4x-to-5x

Thanks!

**Comment by AndreSand** [comment]
@mattdyoung thanks for the links. The v5.x documentation helped me fixed my issue. Thank you.
