### ISSUE TITLE
Update kotlin-stdlib

### ISSUE THREAD

**Issue by M66B** [bugsnag/bugsnag-android#1236]
Currently, bugsnag-android:5.9.1 references kotlin-stdlib:1.3.72, which results in an Android studio build warning:

```
w: Runtime JAR files in the classpath have the version 1.3, which is older than the API version 1.4.
```

So, I guess this library reference needs to be updated.

Dependency graph:

```
+--- com.bugsnag:bugsnag-android:5.9.1
|    +--- com.bugsnag:bugsnag-android-core:5.9.1
|    |    +--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72
|    |         +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.72
|    |         \--- org.jetbrains:annotations:13.0
|    +--- com.bugsnag:bugsnag-plugin-android-anr:5.9.1
|    |    +--- com.bugsnag:bugsnag-android-core:5.9.1 (*)
|    |    +--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
|    +--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 (*)
```

**Comment by johnkiely1** [comment]
Hi @M66B. 

We have been looking into this but have been unable to reproduce the same warning as you are seeing without the conflict coming from the app using Bugsnag itself.

This warning would appear if `org.jetbrains.kotlin:kotlin-gradle-plugin` has been set to 1.4.0 but your `org.jetbrains.kotlin:kotlin-stdlib` has been set to 1.3.0 for example, within your application. 

By setting `org.jetbrains.kotlin:kotlin-stdlib` to 1.4.0 this should remove the warning and Bugsnag will use the newer version as Gradle will automatically and silently pull in the updated dependency.

**Comment by M66B** [comment]
For some reason this warning message disappeared. I am not sure what reason though. Thanks for looking into this anyway.
