### ISSUE TITLE
Bugsnag 3.5+ is not compatible with older Enterprise Server instances

### ISSUE THREAD

**Issue by fcduarte** [bugsnag/bugsnag-android#126]
Hello,

after the implementation of the new Breadcrumb API (#111) when we try to post breadcrumbs using the previous `leaveBreadcrumb(String message)` method, no breadcrumbs are seen in any exception reports.

Unfortunately I don't know which version our Enterprise Server is running, I know it was recently upgraded to the v2 endpoints. 

Also, as a separated enhancement, can you guys start to have a changelog for the Enterprise versions? A mapping between SDK version and server versions would also be good.

Thanks!

**Comment by kattrali** [comment]
Hi @fcduarte, thank you for the report. As this is an issue with Enterprise Server, it would be best to handle this issue via support@bugsnag.com.

> Also, as a separated enhancement, can you guys start to have a changelog for the Enterprise versions? A mapping between SDK version and server versions would also be good.

That's a great idea. I'll raise it with the enterprise team so we can have less confusion in the future.
