### ISSUE TITLE
beforeNotify() gets called multiple times

### ISSUE THREAD

**Issue by jermainedilao** [bugsnag/bugsnag-android#127]
beforeNotify() gets called multiple times. Is it on my side only?

**Comment by kattrali** [comment]
Thanks for the report, @jermainedilao. Are you observing `beforeNotify` being called multiple times for a single error report? What version of bugsnag-android are you using?

**Comment by jermainedilao** [comment]
Yes, for a single error report. However I didnt specify it here. I only
placed "com.bugsnag:bugsnag-android:+" could this be relevant to whats
happening? Thanks for the response.
