### ISSUE TITLE
Use compression for submitting form data

### ISSUE THREAD

**Issue by thebostik** [bugsnag/bugsnag-android#128]
I noticed that the POST data for events is just `Content-Type: application/json` (building this form data is implemented in [HttpClient](https://github.com/bugsnag/bugsnag-android/blob/v3.6.0/src/main/java/com/bugsnag/android/HttpClient.java#L26)).

Is it possible to submit form bodies with gzip compression?

**Comment by Pezzah** [comment]
Thanks for the suggestion, there is no reason why this couldn't work from the Android notifier, but it requires changes in our server code to handle compressed payloads. 

We are starting doing some work on our server soon, so this suggestion may be possible after that

**Comment by kattrali** [comment]
Closing this here, since there isn’t much to be done from the client right now to fix this, but we can revisit once we support this in the API.
