### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by rikur** [bugsnag/bugsnag-android#1285]
https://docs.bugsnag.com/platforms/android/configuration-options/#enabledbreadcrumbtypes
```
config.setEnabledBreadcrumbTypes(new HashSet<String>());
```
should read
```
config.setEnabledBreadcrumbTypes(Collections.<BreadcrumbType>emptySet());
```
I think.. at least it seems to work for me.

**Comment by xander-jones** [comment]
Hi @rikur, good spot 👀 ! Thanks for letting us know about this issue. The fix should just be to make the following change:

```diff
- config.setEnabledBreadcrumbTypes(new HashSet<String>());
+ config.setEnabledBreadcrumbTypes(new HashSet<BreadcrumbType>());
```

Will get this updated in the docs!

**Comment by xander-jones** [comment]
The docs have now been fixed. Thanks again for raising this.
