### ISSUE TITLE
[Question] Network library being used?

### ISSUE THREAD

**Issue by cristianoccazinsp** [bugsnag/bugsnag-android#1327]
Hello, 

Trying to debug a react-native network issue (RN uses okhttp) and I wonder which networking library does this project use.

Basically, the app may end up in a situation where okhttp does not have connectivity, yet bugsnag seems to connect to just fine.

Thanks.

**Comment by yousif-bugsnag** [comment]
Hey @cristianoccazinsp,

`bugsnag-android` uses `HttpURLConnection` to make requests: https://github.com/bugsnag/bugsnag-android/blob/55cbe5b7cb54af43be57a4aee827ed7c9ae750cc/bugsnag-android-core/src/main/java/com/bugsnag/android/DefaultDelivery.kt

Closing this issue out but please feel free to write in to us at support@bugsnag.com if you have any further questions.
