### ISSUE TITLE
Exception while offline?

### ISSUE THREAD

**Issue by pcoughran** [bugsnag/bugsnag-android#133]
If the phone is not connected to the internet (no cell, wifi, etc), will the SDK queue the request until it can successfully send it up? Or will the request just fail and not get to your server?

**Comment by Pezzah** [comment]
Hi

There is code here https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/Client.java#L652 which stores the errors to disk if there is a network error when trying to send the report

**Comment by pcoughran** [comment]
Super, I wasn't finding it. Thanks!

**Comment by haggaishG** [comment]
Where are the errors are stored?

**Comment by xander-jones** [comment]
Hey @haggaishG, I see you reached out at support@bugsnag.com, but for the benefit of future travellers:

The Android notifier will store error events and sessions to disk if there is no internet connection, or if the notifications cannot be delivered for some reason).

We currently store a maximum of 128 events on disk and begin by deleting the oldest errors if the limit has been reached and newer events need to be persisted.

**Comment by haggaishG** [comment]
Many thanks.

Can you please tell me where (directory) those errors are stored?
and will the device send them automatically when the device is back online?

All the best
Haggai

*Haggai Shapira*
Mobile:   052-5015634
Me In Facebook <http://www.facebook.com/haggai.shapira>

**Comment by xander-jones** [comment]
Event reports are stored in a `bugsnag-errors` directory, which is stored in the device’s cache directory. The stored event reports are flushed on the following events:
* Application launch
* Connection change
* When a call to a handled `Bugsnag.notify()` occurs

_**Please note**: the above is implementation detail, and is subject to change._
