### ISSUE TITLE
Crashes not reported by bugsnag

### ISSUE THREAD

**Issue by saurabh0802chd** [bugsnag/bugsnag-android#136]
After application crash if user immediately click "OK" on dialog (having message "Unfortunately, 'Application Name' has stopped) than crash is not getting reported. Device details on which this issue occurs are below:

Manufacturer: Samsung
Model: SM-G313HZ
OS Version- 4.4.2

**Comment by Pezzah** [comment]
There may be an issue here if the application ends before the error has been sent to Bugsnag. We need to make sure it is 100% reliable about reporting exceptions.

I'm thinking about caching the error to disk in a blocking call first (with a max number of reports stored), and then trying to send it async. If the error fails to send then we would retry sending when the application was restarted (and this send attempt could be made blocking). 

We already have this mechanism in place for when a device does not have network connectivity, so it would not be too difficult to expand the functionality.
