### ISSUE TITLE
solicitud de extracion

### ISSUE THREAD

**Issue by Pirunchy75** [bugsnag/bugsnag-android#1604]
### Environment
* Android version:
* Bugsnag version:
* Emulator or physical device:

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by xander-jones** [comment]
Closing as I assume this was raised in error.
