### ISSUE TITLE
Help needed contributing

### ISSUE THREAD

**Issue by guuilp** [bugsnag/bugsnag-android#1741]
Hey everyone!

I'm trying to make a contribution to the `bugsnag-android` project, but I'm having a hard time running the unit tests locally.

Tried to first build the project via command-line (`./gradlew clean assembleRelease`) but I'm having an NDK error, [here's the build scan](https://scans.gradle.com/s/n3qbmvgcvyjxc/activate).

I'm not used to the NDK setup, so I'd appreciate if you could help me! 🙇

**Comment by guuilp** [comment]
Tried to first build the project via command-line (`./gradlew clean assembleRelease`) and received this:

```
C/C++: /Users/guilherme.pereira/Projects/forks/bugsnag-android/bugsnag-plugin-android-ndk/CMakeLists.txt release|armeabi-v7a : CMake Warning at /Users/guilherme.pereira/Library/Android/sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
```

**Comment by luke-belton** [comment]
Hi @guuilp - are you still having trouble with this? Perhaps it's no longer an issue given the resolution of https://github.com/bugsnag/bugsnag-android/pull/1742. Let me know if you want us to look into this further 👍
