### ISSUE TITLE
Why did you make DefaultDelivery as internal ?

### ISSUE THREAD

**Issue by viter-sweatcon** [bugsnag/bugsnag-android#1793]
I want to debug content and size of my events, metadata and so on. Most easy way which I found was to add middleware to `Delivery` but it's no possible with current API. What is a goal of this API decision ? I cant event spoof config to intercept DefaultDelivery creating to wrap it :( Is it possible to change api ?

**Comment by johnkiely1** [comment]
Hi @viter-sweatcon, 

You can create your own `delivery` implementation. Details on how to do this are here: https://docs.bugsnag.com/platforms/android/configuration-options/#delivery 

It's not clear what your use case is exactly but, you can also get access to any/all individual events prior to it being sent via a callback: https://docs.bugsnag.com/platforms/android/customizing-error-reports/#updating-events-using-callbacks 

Hope that helps.

**Comment by johnkiely1** [comment]
Hi @viter-sweatcon, 

I can understand your point, but at the same time I don't think we would want to make the class public either. As a workaround we could suggest you just copy the `DefaultDelivery` [code](https://github.com/bugsnag/bugsnag-android/blob/948d303414678802856a336ad41083036259b48b/bugsnag-android-core/src/main/java/com/bugsnag/android/DefaultDelivery.kt) as your own implementation and then modify this to suit your needs.
