### ISSUE TITLE
BugSnag.isStarted() implementation isn't thread safe

### ISSUE THREAD

**Issue by jgreen210** [bugsnag/bugsnag-android#1795]
### Describe the bug

The BugSnag.isStarted() implementation isn't thread safe: https://github.com/bugsnag/bugsnag-android/pull/1640#discussion_r1072062674

See https://github.com/bugsnag/bugsnag-android/issues/883 too.

**Comment by johnkiely1** [comment]
Hey @jgreen210, 

Thanks for the suggestion. 

A couple of points regarding the current implementation:
  
If `isStarted` returns `true` then `getClient` will not throw an exception, which is expected. 
It is allowed to return `false` while start is in-flight. 

Adding the lock would require isStarted to wait while start completes before returning, which is not always desirable. So is not something we would want to do.

**Comment by jgreen210** [comment]
> Adding the lock would require isStarted to wait while start completes before returning, which is not always desirable. So is not something we would want to do.

OK, but there is still a bug here. If you don't want to obtain the lock in isStarted, then could use an AtomicBoolean to ensure there's a memory barrier. It might also be possible to fix it some other way when fix https://github.com/bugsnag/bugsnag-android/pull/1731#discussion_r1072083465
