### ISSUE TITLE
ActivityBreadcrumbCollector surfaces the wrong activity previous state

### ISSUE THREAD

**Issue by pyricau** [bugsnag/bugsnag-android#1817]
Activity lifecycle state breadcrumbs have a `previous` attribute that surfaces the previous state.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/557033/225156486-9dd4b1f8-a088-4caa-af44-2f665e401d51.png">

Unfortunately, as can be seen here, that previous state is not computed correctly and can be misleading. E.g. here we see an activity is receiving `onStop()` and yet the breadcrumb claims the previous state is `onDestroy()` which is impossible (`onDestroy()` is a final state).

This is happening because ActivityBreadcrumbCollector keeps a single field `prevState` which just stores whatever the last state update was for any activity, not necessarily for the activity that just got a new state.

https://github.com/bugsnag/bugsnag-android/blob/556daed227c2aecf9869a694e0803fb63afc50da/bugsnag-android-core/src/main/java/com/bugsnag/android/ActivityBreadcrumbCollector.kt#LL11C9-L11C18

Apps often have multiple activities having lifecycle events interleaved.

**Comment by lemnik** [comment]
Hi @pyricau 

Thanks so much for pointing this out! We'll have a fix for it out in the next release.

**Comment by johnkiely1** [comment]
The fix for this was released in [v5.29.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.29.0)
