### ISSUE TITLE
Sending native map files failed

### ISSUE THREAD

**Issue by mirage93i** [bugsnag/bugsnag-android#1934]
```
> Task :app:uploadBugsnagNdkReleaseMapping FAILED
Bugsnag: Uploading SO mapping file from <Real path>\arm64-v8a\libsolver0.so.gz

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bugsnagReleaseReleaseTask'.
> java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Bugsnag request failed to complete

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:uploadBugsnagNdkReleaseMapping'.
> java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

```

It is probably related to some security rules in my organization. So I need to add certificate for BugSnag servers to send map files.
But I have not found where is it located and how to get it.

**Comment by mirage93i** [comment]
I've tried to use bugsnag-cli and it looks that this tool works properly without any problem instead of Android Studio

**Comment by mirage93i** [comment]
Very strange it works now.

**Comment by clr182** [comment]
Hi @mirage93i 

This was possibly due to a networking infrastructure issue at your organization. As it looks like this issue has been resolved I am going to close this ticket out. Please feel free to reopen this if the problem arises again or persists
