### ISSUE TITLE
Official binding library for Xamarin

### ISSUE THREAD

**Issue by CAMOBAP795** [bugsnag/bugsnag-android#200]
### Expected behavior
It will be nice to have official Xamarin binding library for android on https://www.nuget.org/

### Observed behavior
There is no official Xamarin binding library for android

### Steps to reproduce
 1. Go to https://www.nuget.org/
 2. Search "Bugsnag" 
 3. Mostly outdate, unofficial 

### Version
Any

**Comment by fractalwrench** [comment]
Thanks for raising this @CAMOBAP795. I'm not too familiar with Xamarin - what would be the steps for creating a binding library? I presume this would also need to apply to iOS.

**Comment by CAMOBAP795** [comment]
> what would be the steps for creating a binding library?

**Comment by CAMOBAP795** [comment]
> what would be the steps for creating a binding library?

1. Open Xamarin IDE or Visual Studio
2. Create Binding library from template
3. Put `bugsnag.aar` in `Jar` directory
4. Make sure that you compiled `bugsnag.aar` with java 7 (because there is problems with with java8 https://forums.xamarin.com/discussion/47490/do-not-use-java-jdk-1-8-when-generating-android-bindings-in-xamarin-studio)
5. Prepare `nuspec` descriptor to publish to NuGet

General steps like this

> I presume this would also need to apply to iOS.
I think so, there is similar template for iOS binding library, but I haven't experience with it yet

**Comment by fractalwrench** [comment]
We don't have any immediate plans to support Xamarin officially at present. You could attempt to find an unofficial library on nuget, or attempt [writing your own notifier](https://docs.bugsnag.com/platforms/writing-a-notifier/).
