### ISSUE TITLE
Bugsnag spawns multiple Bugsnag main thread dispatcher in the scene

### ISSUE THREAD

**Issue by rugvedchavanSSG** [bugsnag/bugsnag-android#2025]
Bugsnag spawns multiple Bugsnag main thread dispatcher in the scene after playing the build in the editor.

**Comment by mclack** [comment]
Hi @rugvedchavanSSG 

Are you able to share some more information on this issue for our further investigation? For example:

- What [version of bugsnag-android](https://github.com/bugsnag/bugsnag-android/releases) are you running?
- What version of Android Studio are you running?
- Are you receiving any error messages? If so, can you share screenshots or logs of these?
- Can you please share any BugSnag configuration code in your app? You may want to refer to the [Android integration guide for BugSnag](https://docs.bugsnag.com/platforms/android/) to ensure the SDK is configured in your app correctly.

As this is a public thread, please feel free to share any additional information with us directly by contacting support@bugsnag.com and referencing the GitHub issue: https://github.com/bugsnag/bugsnag-android/issues/2025

**Comment by rugvedchavanSSG** [comment]
It usually happens if there is an exception while exiting play mode! and if you play again it spawns another one! For a quick fix i just disabled bugsnag in the editor. I was using StartAutomaticallyAtLaunch. The version is 7.7.2
