### ISSUE TITLE
Non-fatal errors (using Bugsnag.notify) are all grouped together if there's a helper function involved

### ISSUE THREAD

**Issue by edenman** [bugsnag/bugsnag-android#207]
### Expected behavior
Non-fatals with a different callsite (even if it's one or two levels up in the stacktrace) should be grouped by callsite.

### Observed behavior
Non-fatals with different callsites are all grouped together.

### Steps to reproduce
- Add a helper "logNonFatalToBugsnag" method, and call that instead of calling `Bugsnag.notify` directly
- Add calls to your helper method from a few different places. 
- Trigger errors from each of those places.
- Note that they are are all grouped together.

### Version
bugsnag-android:4.0.0

### Additional information
I'm guessing we need something like iOS's `report.depth` to tell bugsnag how to group non-fatals when there's a helper method involved.

Example issue:
https://app.bugsnag.com/recharge-labs/android/errors/59dfe2b4855ea5001993998c

**Comment by fractalwrench** [comment]
Thanks for the report @edenman - it would definitely make sense to offer something similar to the `report.depth` functionality on iOS.

There are a couple of ways to achieve the desired behaviour in the SDK currently. The first approach would be to specify a [custom grouping hash](https://docs.bugsnag.com/platforms/android/sdk/customizing-error-reports/#setgroupinghash), e.g. using the log message. The other approach would be to [modify the stacktrace in a callback](https://docs.bugsnag.com/platforms/android/sdk/customizing-error-reports/#modifying-the-stack-trace) and remove the number of frames required.

I think it makes sense to add this functionality into the SDK, as it's a common usecase. Perhaps we could expose something like the following:

```
Bugsnag.beforeNotify(new BeforeNotify() {
    @Override
    public boolean run(Error error) {
        error.discardTopStackFrames(5);
        return true;
    }
});
```

**Comment by edenman** [comment]
Custom grouping hash doesn't work for me.  The helper method exists to take care of the nitty-gritty details, but still get grouping by stacktrace.

It'd be a little weird to have `beforeNotify` be a top-level hook, bc then I'd have to branch on whether the error was a manually logged one vs an uncaught exception (we don't want to remove any stack elements for the latter).  

I just realized there's a `Bugsnag.notify(name, message, stacktrace, callback)` so I _think_ I can just manually grab the stacktrace and remove the top element myself.  Gonna try that.

**Comment by edenman** [comment]
The "manually pruning the stacktrace" approach seems to be working so I'm just gonna do that.  Feel free to close this (or leave open if you're planning on doing something more like the `depth` approach on iOS)
