### ISSUE TITLE
Too many system-generated breadcrumbs

### ISSUE THREAD

**Issue by edenman** [bugsnag/bugsnag-android#210]
### Observed behavior
There are sometimes _tons_ of system-generated breadcrumbs in crash reports.  While these are sometimes very useful, [in other cases](https://app.bugsnag.com/recharge-labs/android/errors/599f44e42b4c9d001846d05f) they can completely crowd out the breadcrumbs manually inserted by my app.

### Version
4.0.0 (i've upgraded to 4.1.3 on master, just haven't released it yet)

I'm not sure what the right fix is here: some devices are likely going to just be chattier than others.  And certain situations (changing wifi networks) will generate _way_ more system breadcrumbs than others.  Maybe system breadcrumbs could be put in a different quota so `setMaxBreadcrumbs` doesn't apply to them?  Or allow apps to customize which system broadcasts they care about?

**Comment by kattrali** [comment]
Thanks for the report, @edenman. I've been thinking about this as well. There are few options here:

* Caching system- and user- breadcrumbs separately: Solves the problem but is potentially deceptive as interleaved breadcrumbs would then drop system breadcrumbs first, which may indicate an incorrect user flow leading up to an error.
* Disabling breadcrumbs by type: We could be more strict about breadcrumb types and allow disabling them in large chunks
* Disabling individual breadcrumb types? There might be specific noisy events which are never important, though in that case I'd rather have it filed as an issue and we consider not enabling it by default.

**Comment by edenman** [comment]
- Caching separately: that's a totally valid point.
- Disabling by what kind of system event it is: yeah, I'm certainly ok with ignoring `android.net.wifi.SCAN_RESULTS` and `android.net.wifi.supplicant.STATE_CHANGE`, but maybe there are apps where those events are actually super-useful?  Probably not really?  I dunno.

**Comment by kattrali** [comment]
I took a sample of several different dashboards, and I think turning those two off in particular is for the best. They're either not common or extremely noisy between different error reports of the same type.

**Comment by fractalwrench** [comment]
The two wifi events have been removed from automatic capture in 4.1.5, along with some other potentially noisy breadcrumbs. The default maximum breadcrumb count has also been increased to 32 in reflection of the fact that we're now capturing a lot more information than just manual breadcrumbs.

If you do run across other noisy breadcrumbs please get in touch.
