### ISSUE TITLE
Automatic Breadcrumbs and sensitive data

### ISSUE THREAD

**Issue by kenumir** [bugsnag/bugsnag-android#221]
Automatic Breadcrumbs are grat but log user sensitive data like WiFi network name or incoming call phone numer if application has permissions.

It would be great if you could cut out this data - privacy policy.

**Comment by fractalwrench** [comment]
Thanks for the suggestion @kenumir - this makes a lot of sense. We've recently added a [configuration option](https://github.com/bugsnag/bugsnag-android/blob/master/sdk/src/main/java/com/bugsnag/android/Configuration.java#L466) to disable automatic breadcrumbs entirely.

We're also planning on adding an API which allows you to filter breadcrumbs, which would work similarly to how [beforeNotify does currently](https://docs.bugsnag.com/platforms/android/sdk/#attaching-custom-diagnostics).
