### ISSUE TITLE
Code maintenance/refactor ideas

### ISSUE THREAD

**Issue by d4rken** [bugsnag/bugsnag-android#269]
Some thoughts on SDK improvements as requested by @fractalwrench :

* `DeviceData` and `DeviceDataSummary` could need some love, why the class split?
* Pull out `Client.notify` and `Client.deliver` and access to `errorStore` from `Client` into an extra component.
* Refactor (remove) the need for `Notifier.getInstance()`. We can do without a static singleton. Easier to test (I think there are no tests for this component currently?).
* Move away from `androidTest` and run pure java unit tests. Makes for an easier test stack/CI (also works towards merging some code between the bugsnag Android/Java SDK). I've had good experiences with [mockwebserver](https://github.com/square/okhttp/tree/master/mockwebserver) to do non `androidTest` tests.

**Comment by fractalwrench** [comment]
`DeviceDataSummary` is used for our Session Tracking API, which requires fewer fields than our Error Reporting API. It would probably be worth extracting out the Android-specific calls from this class, as the Java Notifier uses a very similar approach.

Did you mean a class by an extra component or something else like a module? It definitely makes sense to split out the notification and delivery process as they're two separate activities.

It'd probably make sense to allow setting the Notifier instance as an internal API, as other notifiers like bugsnag-unity currently modify this value, and this would get rid of the singleton.

That's definitely a good suggestion, although test runtimes aren't a particular worry at the moment on local builds. It'd be nice to setup the infrastructure to run pure JVM tests, and abstract away a few more of the Android APIs from parts of the code.

**Comment by johnkiely1** [comment]
All these suggestions have been addressed in [V5.0.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.0.0)

- DeviceWithState is a structured class on Error, Device is on Session as sessions only contain stateless application info
- The implementation of Client has been split out into various smaller classes
- Notifier is no longer a singleton
- The majority of tests now run on the JVM
