### ISSUE TITLE
Multiple Exceptions Thrown to Bugsnag

### ISSUE THREAD

**Issue by AllanWang** [bugsnag/bugsnag-android#283]
Bugsnag v4.3.2
Bugsnag plugin v3.2.5

![image](https://user-images.githubusercontent.com/6251823/38458844-8e009aba-3a70-11e8-8006-75848040be4a.png)

There isn't much for me to say about reproducing this, but I have a scroll event issue that supposedly crashes the app, that has managed to be produced 3 times in 3 seconds. How is that possible, and is there any chance Bugsnag is either duplicating the issue or calling it multiple times for the same issue?

I've looked around at other events and they are typically working as expected (one event per exception)

**Comment by fractalwrench** [comment]
Thanks for reporting this @AllanWang - this looks like an occurrence of #270, which was resolved in v4.3.3.
