### ISSUE TITLE
Cannot use two client instances with different API keys

### ISSUE THREAD

**Issue by pyricau** [bugsnag/bugsnag-android#285]
### Expected behavior
Let's say I create two distinct Bugsnag clients, like so:

```
Client client1 = new Client(application, "key1", false);
Client client2 = new Client(application, "key2", false)
```

These two clients use two distinct keys, and are expected to upload errors to two distinct bugsnag projects.

### Observed behavior

If there is no network when we try to notify and the errors get stored on the filesystem, the API keys stored in the errors will be ignored and the errors will be uploaded to the project of whichever client flushes first.

### Steps to reproduce

* Turn of Wifi
* Create a client instance with API KEY 1
* Send an error to client (it gets stored because no wifi)
* Kill the app
* Start the app
* Create a client instance with API KEY 2, get it to flush
* => the crash 1 gets uploaded to project 2 instead of project 1.

### Version
Still happening on master, all releases have this bug.

### Additional information

At this line: https://github.com/bugsnag/bugsnag-android/blob/master/sdk/src/main/java/com/bugsnag/android/ErrorStore.java#L125

```java
    private void flushErrorReport(File errorFile, ErrorReportApiClient errorReportApiClient) {
        try {
            Report report = new Report(config.getApiKey(), errorFile);
            errorReportApiClient.postReport(config.getEndpoint(), report,
                config.getErrorApiHeaders());
// ...
```

The report is uploaded with the API Key from the config of the error store, not the API Key from that config that was used when the error was created (that config is actually stored in the error).

### Possible solutions

1) Allow customizing the error store and session store folders. This would allow each client to store data in a distinct folder and avoid clients stepping over each other
2) Read the content of the error before uploading it, to retrieve the proper API key. This is potentially risky.
3) Fix this server side, check for Error file content with config.apiKey set to something different than the API Key that was used to upload.

**Comment by fractalwrench** [comment]
Thanks for the detailed report @pyricau - I can see that the current `ErrorStore` implementation is problematic for the apiKey, endpoint, and headers, if multiple clients are instantiated. I'll start writing some test cases for these scenarios and discuss with the rest of the team what the best solution is.

**Comment by felipehjcosta** [comment]
Hi guys! 
Any plan to add this feature in the future?

**Comment by alexjlockwood** [comment]
Anyone have any potential workarounds for this issue?

**Comment by mattdyoung** [comment]
Hi

Thanks for your thoughts, but just an update to say that after much discussion we'd like to state that we have no current plans to implement this feature. The work is fairly significant to make this work on our iOS notifier (to provide consistency of features with Android) and it would be difficult to make the behaviour sensible with how sessions are handled.

It would also add fairly heavily to our testing burden to have to consider this scenario for all future development.

**Comment by pyricau** [comment]
Thanks @mattdyoung . Just to be very clear, this means Square will either have to fork bugsnag-android or move on from Bugsnag.

**Comment by JakeWharton** [comment]
s/Square/one of Square's apps/

**Comment by snmaynard** [comment]
You can now set the [apikey on an Event](https://docs.bugsnag.com/platforms/android/customizing-error-reports/#apikey) basis, so you'd only have to have one Client with all the memory overhead etc that entails. Does that let you solve this use case?

**Comment by pyricau** [comment]
Unfortunately, I don't believe this is fixed, unless you fixed the server side as well. The underlying issue here is that when flushing on launch, Bugsnag Android uses the config API key instead of reading the report API key.


See `config.getApiKey()` in https://github.com/bugsnag/bugsnag-android/blob/e6d6890a4662b26706ae676a78d320aa8d6d2893/bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java#L149 :

```
    private void flushErrorReport(File errorFile) {
        try {
            Report report;

            if (config.getBeforeSendTasks().isEmpty()) {
                report = new Report(config.getApiKey(), errorFile);
            } else {
                Error error = ErrorReader.readError(config, errorFile);
                report = new Report(config.getApiKey(), error);
```

This decision was maybe made so that apps can update their key and upload crashes stored from the previous version to the new version. As a result though, it means the event API key isn't used for upload.

What's the server behavior here? Does it now try with the event's API key first?

This was a huge issue for us when we shipped an SDK with bugsnag and a customer also had bugsnag, crashes & warnings would be randomly sent to either project.

**Comment by snmaynard** [comment]
I think you are correct that right now that won't work, but that is definitely something that we should make work. If that was to work (you could change an apikey in an onError callback) would that solve your use case?

**Comment by pyricau** [comment]
If the events ended up in the project of the api key they were assigned to, it would definitely solve my problem. However, I don't think "change the api key in on error"

The key underlying issue here is that all crashes are stored in the same directory no matter the api key / number of clients. And when flushing on startup these events are not deserialized, they're sent as in with whatever the api key of the client. If you create 2 client instances, they both try to flush the *same* directory when created, and each uses their own self API key to upload instead of the api key of the file. Overriding onError would not change anything about that, since that's called before the object is serialized afaik.

**Comment by snmaynard** [comment]
We are actually working on both - the ability to control the location of the reports in `Client` configuration and also making it so you can control the apikey in the `onError` callback.

I'd recommend having a single `Client` per process as they come with a reasonable memory overhead, but I'm sure there are occasions where having two is desirable nonetheless.

Hopefully when those fixes get shipped that makes it easy for you to do what you need.

**Comment by pyricau** [comment]
Unfortunately I suspect supporting both these cases still does not cover the use case I've been referring to. The onError callback is invoked prior to writing the event to disk, AFAIK. The issue here is that, later on, the files on disk are flushed and sent to the server, and their API key is ignored, and instead the client instance's key is used.

**Comment by snmaynard** [comment]
That would no longer happen, the apikey supplied in the `onError` would be the one used.

**Comment by pyricau** [comment]
Oh, sounds great then!

**Comment by johnkiely1** [comment]
Hi @pyricau,

As of release [v5.5.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.5.0) we have now added the ability to configure the persistence directory location.
Detailed instructions on how to use this are available in the [documentation](https://docs.bugsnag.com/platforms/android/faq/#does-bugsnag-support-multi-process-apps).

Hopefully this gives you a solution, let us know how you get on.
