### ISSUE TITLE
Breadcrumbs uploaded with new SDK display weirdly in web UI

### ISSUE THREAD

**Issue by edenman** [bugsnag/bugsnag-android#291]
### Expected behavior
Breadcrumbs display with the full message

### Observed behavior
https://app.bugsnag.com/recharge-labs/android/errors/5ad8db56c0ebd600182ae1ea has breadcrumbs but the message is crammed into the left side and the full message is not shown

### Steps to reproduce
1. Upgrade to com.bugsnag:bugsnag-android:4.3.3 (from 4.1.5, if that matters)
2. Set some breadcrumbs using `Bugsnag.leaveBreadcrumb(message)`
3. Force the app to crash

### Version
4.3.3

**Comment by edenman** [comment]
Thanks!  I couldn't tell if it was a dashboard thing or a client thing.

**Comment by edenman** [comment]
@fractalwrench any update on this?  it makes breadcrumb analysis entirely useless.

**Comment by fractalwrench** [comment]
@edenman there appears to be an issue with the 4.3.3 client where the breadcrumb message is serialised as the title instead, leading to truncated text on the dashboard.

Additionally, there's a layout issue with long breadcrumbs that our dashboard team is working to address separately (example below)

<img width="232" alt="screen shot 2018-05-01 at 10 30 03" src="https://user-images.githubusercontent.com/11800640/39468386-a4caad68-4d2a-11e8-860e-43dac822e954.png">

**Comment by edenman** [comment]
That's unfortunate.  Let me know when there's a fix for the client serialization issue?

**Comment by fractalwrench** [comment]
A fix for this issue should now be available in [v4.3.4](https://github.com/bugsnag/bugsnag-android/releases/tag/v4.3.4).
