### ISSUE TITLE
Crashes aren't being reported immediately on Android P

### ISSUE THREAD

**Issue by mattprecious** [bugsnag/bugsnag-android#318]
### Expected behavior
Crashes on P are reported

### Observed behavior
Crashes on P are not reported

### Steps to reproduce
Crash the app on P

### Version
4.4.0

### Additional information
It seems that P is being more aggressive in killing processes after a crash.

The error is persisted to disk successfully [here](https://github.com/bugsnag/bugsnag-android/blob/master/sdk/src/main/java/com/bugsnag/android/Client.java#L929), but the process is killed before `flushReports` is called asynchronously [here](https://github.com/bugsnag/bugsnag-android/blob/master/sdk/src/main/java/com/bugsnag/android/ErrorStore.java#L100).

When the app is started again, [`flushOnLaunch`](https://github.com/bugsnag/bugsnag-android/blob/master/sdk/src/main/java/com/bugsnag/android/ErrorStore.java#L53) is called but `flushAsync` is never invoked because the stored report is being filtered out from `findLaunchCrashReports()` [here](https://github.com/bugsnag/bugsnag-android/blob/master/sdk/src/main/java/com/bugsnag/android/ErrorStore.java#L54).

It seems that, as implemented, the only way to successfully report persisted crashes is to disable the launch crash threshold.

**Comment by mattprecious** [comment]
It eventually came in... I updated the app and it reported the crash from 40m prior. Not sure what hook was invoked for that.

**Comment by kattrali** [comment]
Thanks for the report, @mattprecious. It looks like we'll need to make some adjustments to account for reports not being sent at crash time.

**Comment by fractalwrench** [comment]
Fixed in v4.4.1
