### ISSUE TITLE
StackOverflowException fails to be reported because of SSLException writing it

### ISSUE THREAD

**Issue by AlecStrong** [bugsnag/bugsnag-android#322]
### Expected behavior
StackOverflowException that occurs is reported to bugsnag

### Observed behavior
Bugsnag crashes silently when trying to report the issue

### Steps to reproduce
Cause a StackOverflowException with an enormous stacktrace (mine has 506,000 StackTraceelements

### Version
4.4.0

### Additional information
The exception happens here: https://github.com/bugsnag/bugsnag-android/blob/master/sdk/src/main/java/com/bugsnag/android/Stacktrace.java#L37

This is the exception: `javax.net.ssl.SSLException: Write error: ssl=0x8c2bd1c0: I/O error during system call, Broken pipe`

And it is likely caused because the `stacktrace` variable in that code has 506,000 elements and writing all of those is itself causing an out of space issue. I think ideally you max out how many elements we try to print?

Short of that, printing to syster err doesnt so anything to help us on Android, as I dont think those get printed to logcat or anything. If possible bugsnag should itself crash if theres a problem I would think, so its easier to catch and report issues like this

**Comment by JakeWharton** [comment]
Android does redirect stdout and stderr to logcat (https://android.googlesource.com/platform/frameworks/base/+/master/core/java/com/android/internal/os/RuntimeInit.java#371) but you're subject to the limits of the struct which ferries the message to logcat which has a message limit of 4023 characters.

**Comment by AlecStrong** [comment]
cool. Im not seeing the SSLException in logcat anywhere so im assuming it is hitting that limit

**Comment by fractalwrench** [comment]
Thanks for the detailed report @AlecStrong. I think it would probably make sense for us to drop stackframes after a certain reasonable limit is reached (e.g. 1000) and display some indication that data was removed in the dashboard. We may also want to remove printing the stacktrace or put it through our `Logger` class, which is automatically disabled in production builds.

**Comment by AlecStrong** [comment]
sounds good, google play appears to limit to 125 frames for context

**Comment by fractalwrench** [comment]
Resolved in v4.5.0
