### ISSUE TITLE
Investigate BuildConfig.DEBUG for better releaseStage detection

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-android#36]
Investigate BuildConfig.DEBUG for better releaseStage detection: http://stackoverflow.com/a/25267049/102542

**Comment by leonardoxh** [comment]
A good way to see this in pratice is with Jake Warton's timber library:

https://github.com/JakeWharton/timber

;)

**Comment by Pezzah** [comment]
I've had a look into this and I can't seem to get it to work reliably using Android Studio
