### ISSUE TITLE
How can I update the name and screen of a handled exception?

### ISSUE THREAD

**Issue by ColtonIdle** [bugsnag/bugsnag-android#437]
My team is doing a lot of handled exceptions and logging them in BugSnag as well. We have similar needs as https://github.com/bugsnag/bugsnag-android/issues/207

That is, just better support for non-fatal exceptions.

Our biggest wish so far is how can we set the name and screen of an event in BugSnag?

<img width="424" alt="screen shot 2019-03-06 at 3 01 05 am" src="https://user-images.githubusercontent.com/31751141/53850669-5b51cd80-3fbc-11e9-9e4f-c8b3d77e2c5d.png">

In this case, I'm referring to `android.view.inflateException` as *name* and `MenuActivity` as `screen`.

When we're manually notifying exceptions, we currently do something like:

`Bugsnag.notify(Throwable(Another Picasso network failure), Severity.INFO)`

The issue with the above is that we sometimes call it in different branches of the same class, but they all get grouped together. So yes, we do want different grouping in bugsnag, BUT we also want to set the name and screen just as easily to something human readable so we don't have to decipher it in Timeline view.

Even if we call 

`Bugsnag.notify(Throwable(Another Picasso network failure), Severity.INFO)`

and

`Bugsnag.notify(Throwable(Another Glide network failure), Severity.INFO)`

they show up in the same event grouping! Not only that, but when we are scanning the events, an event of `java.lang.Throwable` `MyActivity` doesn't make any sense. We would love to be able to set the name as "Known issue" and screen as "PicassoModule" for example.

I don't know if maybe we're missing something critical here, but it just seems like we want better non-fatal error messaging control. As stated in #207 we want to distinctly separate out our manually notifys  because they are typically being called from a central place, but in a conditional we would like to say "Actually these are one group of errors, name them X and screen is Y, while these errors are a different group, and name them A and screen is B."

Just to add more context, we also don't care about stack trace in this case. We mostly just care to see that this error is happening X times. Which brings me back to the question that I said earlier, maybe we're just using BugSnag incorrectly, maybe it's not the right hammer for this nail, but in this case we do feel like BugSnag is the right tool for us.

Sorry for the run on description here, but would be glad to talk it out in this thread and curious to see what others think.

**Comment by fractalwrench** [comment]
Thanks for getting in touch @ColtonIdle - there are a couple of strategies that you could use for grouping errors, which are listed fully in [our docs](https://docs.bugsnag.com/product/error-grouping/). In your example `MenuActivity` is the error context, which you could set to "PicassoModule" by calling [setContext](https://docs.bugsnag.com/platforms/android/sdk/configuration-options/#setcontext) either at the appropriate time in your application or in a [callback](https://docs.bugsnag.com/platforms/android/sdk/customizing-error-reports/#adding-callbacks). If these approaches don't satisfy your needs, it would also be possible to set a [custom grouping hash](https://docs.bugsnag.com/product/error-grouping/#custom-grouping-hash).

As this isn't a bug with the library we'd recommend that you get in touch with support@bugsnag.com who will be able to assist you with grouping.

**Comment by ColtonIdle** [comment]
@fractalwrench thanks for the response. I didn't see the grouping docs before as I was searching in the Android docs specifically and the best I found was https://docs.bugsnag.com/platforms/android/customizing-error-reports/

I see that I can also setContext. That's also helpful and solves 2/3 out of my issues. Any chance that I can set the actual name of the exception instead of `java.lang.Throwable`?

Sorry for asking here by the way. I'll go to support next time!
