### ISSUE TITLE
Expose unhandled exceptions in the Client API

### ISSUE THREAD

**Issue by pyricau** [bugsnag/bugsnag-android#446]
Square disables the automated crash reporting, we have our own uncaught exception handler installed and it calls bugsnag on our own terms. That's been working great so far.

Bugsnag added tagging of handled / unhandled exceptions a while back but didn't expose an API for it. We'd like an API to notify of unhandled exceptions.

**Comment by snmaynard** [comment]
Thanks for the feedback @pyricau! We track our product roadmap internally and I have registered your interest in this there. We'll close this for now so we don't double track it - but we'll ping you back here when this is shipped!
