### ISSUE TITLE
All native crashes are being reported as emulator / jailbroken devices

### ISSUE THREAD

**Issue by alizons** [bugsnag/bugsnag-android#447]
### Expected behavior
Native crashes are reported correctly in terms of emulator and jailbroken tags

### Observed behavior
All native crashes are being reported with metatags "emulator" : true, "jailbroken" : true

### Steps to reproduce
Create a project with C++ layer and JNI bridging. Force crash in C++ (For example SIGKILL)

### Version
com.bugsnag:bugsnag-android-gradle-plugin:3.6.0

Hi guys, 

For some reason Bugsnag is marking all our C++ crashes coming from jailbroken / emulator devices. We have thousands of those and there is no way they all coming from emulators... 
Please see attached screenshot. Wanted to know if it is expected behavior or not.

![export](https://user-images.githubusercontent.com/1931318/55367825-c4d1d880-54a3-11e9-9369-fa80a0d3802a.png)

**Comment by snmaynard** [comment]
This has been fixed in 4.13.0 -> https://github.com/bugsnag/bugsnag-android/releases/tag/v4.13.0 Thanks for reporting it to us!
