### ISSUE TITLE
Warning about using an obsolete API: variant.getPackageLibraryProvider()

### ISSUE THREAD

**Issue by DaanGeurts** [bugsnag/bugsnag-android#473]
### Expected behavior
Running Gradle tasks without warnings

### Observed behavior
Getting warnings about using an obsolete API usage:

> WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'

### Steps to reproduce
implementation 'com.bugsnag:bugsnag-android:4.13.0'

Run Gradle Sync and the errors appears in the build console:
![Screenshot 2019-04-19 at 07 46 02](https://user-images.githubusercontent.com/2170399/56408997-446af000-6277-11e9-8a50-60117ac46a05.png)
 see attached file

### Version
4.13.0

**Comment by fractalwrench** [comment]
Hi @DaanGeurts - thanks for getting in touch. Would you be able to share the version of the bugsnag gradle plugin you're using, along with a stacktrace obtained from gradle with the flag `-Pandroid.debug.obsoleteApi=true`?

**Comment by DaanGeurts** [comment]
Hi @fractalwrench, 
I'm using `com.bugsnag:bugsnag-android-gradle-plugin:3.4.1` and I've attached the stacktrace. 
[gradle_log.txt](https://github.com/bugsnag/bugsnag-android/files/3130332/gradle_log.txt)

**Comment by fractalwrench** [comment]
This was addressed in [v4.0.0](https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v4.0.0), if you could update to the latest version of the plugin this issue should be resolved.
