### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by ychescale9** [bugsnag/bugsnag-android#504]
Currently the SDK depends on the `com.android.support:support-annotations` dependency. It would be good to migrate to the AndroidX version as most libraries do so we can eventually drop the jetifier in projects with no transitive support lib dependencies.

### Version
v4.15.0

**Comment by JakeWharton** [comment]
It's worth noting though that it shouldn't be a problem to have this annotation dependency even with jetifier disabled. And the inverse is true, migrating to AndroidX annotations won't actually force your consumers to have migrated to AndroidX.

**Comment by fractalwrench** [comment]
Thanks for getting in touch @ychescale9. It should already be possible to disable the jetifier if you're only including bugsnag-android in a project that uses `androidx` - I've tested this in an example app and haven't run into any compilation or classpath issues.

Longer-term we'd like to migrate over to the androidx dependency but we need to wait until the majority of users have moved across to use the new namespace. E.g. React Native doesn't currently use androidx by default, and as our React Native SDK depends on bugsnag-android, we're constrained by that.

**Comment by ychescale9** [comment]
Noted. Thanks.
