### ISSUE TITLE
Native libraries are include when bugsnag.ndk = false (reopen)

### ISSUE THREAD

**Issue by kenumir** [bugsnag/bugsnag-android#535]
After update plugin to version 4.5.2 and bungsnag to version 4.17.0 still have `libbugsnag-ndk.so` and `libbugsnag-plugin-android-anr.so` for each architecture.

In manifest file have:
```
<meta-data android:name="com.bugsnag.android.DETECT_NDK_CRASHES" android:value="false"/>
<meta-data android:name="com.bugsnag.android.DETECT_ANRS" android:value="false"/>
```

and `build.gadle`
```
bugsnag {
  ndk false
}
...
implementation("com.bugsnag:bugsnag-android:$version") {
    exclude group: "com.bugsnag", module: "bugsnag-plugin-android-anr"
    exclude group: "com.bugsnag", module: "bugsnag-plugin-android-ndk"
}
```
The output apk file is larger than before

**Comment by mattdyoung** [comment]
Hi @kenumir 

We can't reproduce what you're seeing using v4.17.0 of bugsnag-android and v4.5.2. We built an APK with our integration instructions both with and without the exclude rules. If the exclude rules were specified, there was no ‘lib’ folder in the APK when viewed through the APK Analyzer.

How are you determining that `libbugsnag-ndk.so` and `libbugsnag-plugin-android-anr.so` are included? Are you viewing this in APK Analyzer or just looking at the raw APK size? Is it possible you didn't perform a clean build after updating the gradle configuration?

**Comment by kenumir** [comment]
My gradle file:

```
apply plugin: 'com.bugsnag.android.gradle'

android {
...
   bugsnag {
        ndk false
    }
...

dependences {
...
    implementation("com.bugsnag:bugsnag-android:$versions.bugsnag") {
        exclude group: "com.bugsnag", module: "bugsnag-plugin-android-anr"
        exclude group: "com.bugsnag", module: "bugsnag-plugin-android-ndk"
    }
...
}
}
```

Manifest
```
<meta-data
            android:name="com.bugsnag.android.API_KEY"
            android:value="<my key>"/>
<meta-data android:name="com.bugsnag.android.DETECT_NDK_CRASHES" android:value="false"/>
<meta-data android:name="com.bugsnag.android.DETECT_ANRS" android:value="false"/>
```

Apk analyzer screen (production apk):
![bs](https://user-images.githubusercontent.com/1758624/61791517-7eb9cf80-ae1a-11e9-9617-a15f34a7572d.png)

Bugsnag native libraries are included.

What i doing wrong?

**Comment by fractalwrench** [comment]
Hi @kenumir what is the value of `$versions.bugsnag` and have you performed a clean build/synced gradle? We are unable to reproduce this when performing a clean build on v4.17.0 of bugsnag-android.

`dependences` should be `dependencies` and the `bugsnag` closure should be outside of the `android` closure - are these named correctly in your build script?

**Comment by kenumir** [comment]
`$versions.bugsnag = 4.17.0`

I clean project before build apk (Build->Clean Project & Build->Rebuild Project)

Plugin version is: `classpath 'com.bugsnag:bugsnag-android-gradle-plugin:4.5.2'`

No i hadcoded version like this:
```
implementation("com.bugsnag:bugsnag-android:4.17.0") {
        exclude group: "com.bugsnag", module: "bugsnag-plugin-android-anr"
        exclude group: "com.bugsnag", module: "bugsnag-plugin-android-ndk"
}
```

`dependencies` is outside `android` closure (my mistake when paste from script)

**Comment by fractalwrench** [comment]
@kenumir no SO files are included in the APK when I test this out in an example app with the following configuration, in a fresh build:

```
dependencies {
    implementation("com.bugsnag:bugsnag-android:4.17.0") {
        exclude group: "com.bugsnag", module: "bugsnag-plugin-android-anr"
        exclude group: "com.bugsnag", module: "bugsnag-plugin-android-ndk"
    }
}

apply plugin: "com.bugsnag.android.gradle"
bugsnag.failOnUploadError = false
```

<img width="310" alt="Screenshot 2019-07-24 at 15 20 08" src="https://user-images.githubusercontent.com/11800640/61801413-a31ba900-ae26-11e9-8daa-aba7dfe0def1.png">

Are you able to produce and share a minimal example app that reproduces the problem?

**Comment by kenumir** [comment]
Minimal example works ok. No SO files included.
I am looking for what is wrong in my project.

**Comment by fractalwrench** [comment]
@kenumir are you able to add in additional complexity from your project into the minimal example until the observed behaviour occurs?

**Comment by kenumir** [comment]
I am looking all the time what is wrong, what causes this behavior, I add libraries used in the project, etc. but so far I could not get to what causes this effect

**Comment by kenumir** [comment]
Ok, I found out what's going on.
In the project I have a library that joins bugsnag without the option 'exclude'. This resulted in attaching SO files.
