### ISSUE TITLE
BeforeSend.run report.getError().getException() returns BugsnagException

### ISSUE THREAD

**Issue by M66B** [bugsnag/bugsnag-android#577]
### Expected behavior
return original exception

### Observed behavior
returns BugsnagException

### Steps to reproduce
Use version 4.18+

### Version
4.18+

### Additional information
The return type of report.getError().getException() should either be a Throwable or a BugsnagException. Throwable is preferred because instanceof can be used to quickly and safely determine the exception type, whereas BugsnagException requires a string compare on the exception name.

**Comment by M66B** [comment]
*getException Returns the thrown Throwable.*

https://docs.bugsnag.com/platforms/android/customizing-error-reports/#getexception

**Comment by mattdyoung** [comment]
Hi @M66B 

Thanks for the feedback!

Yes, this is definitely an inconsistency between the behaviour and the documentation but I'm not sure we'd be able to implement your proposed solution as in the general case the error report may be stored and delivered later (e.g. if the app is offline or crashes before the report can be sent). In these cases I don't think we can easily re-create the original exception using the right class.

We'll discuss this and agree the way forward, which may just be to align the documentation with the true behaviour if that's the best we can do.

**Comment by M66B** [comment]
I think this is rather disappointing, especially because it is a breaking change.

I had lots of exceptions unnecessary reported due to this change, hitting the rate limit.

**Comment by M66B** [comment]
Is there any news on this or am I stuck on an old Bugsnag version?

**Comment by tomlongridge** [comment]
@M66B - unless I misunderstand your use case, you shouldn't need to stay on the older version. 

To summarise, the behaviour is that a `BugsnagException` (subclass of `Throwable`) is now always returned whereas previously this was only used for non-JVM (i.e. NDK) errors. From this `BugsnagException` object, the `getCause` method will return the `Throwable` that caused the problem if it's available.

However this return value should be null-checked before use as it will be null if:

* the error didn't originate from the JVM
* you attempt to access it in [a `beforeSend` callback](https://docs.bugsnag.com/platforms/android/customizing-error-reports/#pre-delivery-callbacks) and the report has been serialised to disk -- i.e. the report is not being sent at the time of the crash due to lack of network connectivity. (Note that the above is only the case for `beforeSend` - it _will_ be present in a `beforeNotify` callback for a JVM error as this is always triggered at crash-time.)

**Comment by M66B** [comment]
Thanks for clarifying @tomlongridge 

I have moved my custom checks from *beforeSend* to *beforeNotify* and switched to *error.getException().getCause()*. Can you please confirm this is what you meant?

May I suggest to change the return type of *getException* to *BugsnagException* ?

**Comment by tomlongridge** [comment]
@M66B - yes, that's correct.

We're looking at a documentation update to clarify this.

**Comment by M66B** [comment]
Unfortunately, things do not work as expected: *beforeNotify* seems not to be called, so I had to revert the referenced commit to downgrade Bugsnag again :-(

What can be the cause of this?

**Comment by tomlongridge** [comment]
The changes referenced look OK to me.

One thing to mention is that only JVM errors trigger the `beforeNotify` (see [Adding Callbacks](https://docs.bugsnag.com/platforms/android/customizing-error-reports/#adding-callbacks)), but I presume you're trying this with Java exceptions?

Have you been able to determine that `beforeNotify` isn't triggered at all, as opposed to exiting early in one of the conditionals (from line 219)? I'm not aware of any issues between these two versions with this not firing, so my recommendation would be to remove as much complexity from the callback as possible and check via a debugger or logger whether the callback is fired.

**Comment by M66B** [comment]
The problem appears to be that calling *Bugsnag.notify* results in an empty *error.getException().getCause()* in *beforeNotify*.

Since the app catches most exceptions and reports these with *Bugsnag.notify* (which will filter a number of exceptions) this is not going to work :-(

**Comment by M66B** [comment]
I didn't test this, but I am wondering if *setIgnoreClasses* does work in this case. Not that it will be useful because custom filtering is done to filter exception 'contains' or 'startsWith' *getMessage*.

**Comment by M66B** [comment]
Bugsnag has been quite useful, but I am considering recent versions as broken. In any case there were undocumented breaking API changes. Therefore this issue should not be closed.

Note that I don't mean this in a bad way.

**Comment by M66B** [comment]
Proposal: why not add a callback for custom filtering based on the original exception?

**Comment by M66B** [comment]
No worries @tomlongridge As developer I understand that development isn't easy!

Unfortunately, *getExceptionName* won't work in my case because the exception message needs to be checked as well and sometimes also the underlying cause exception.

Background: JavaMail throws *MessagingException* for everything and anything and the custom logic is meant to filter things away that are no problem (like connection errors).

Maybe I can use the main thread last chance exception handler to do this, but it would be better if there was a working "before" hook for this in Bugsnag.

I guess this issue needs to be reopened until there is a solution for this.

**Comment by mattdyoung** [comment]
We're reworking this area in the next major release and can confirm that the use case you describe will be supported by the changes.

**Comment by M66B** [comment]
@mattdyoung Thanks for letting me know!

**Comment by mattdyoung** [comment]
The interface has now been reworked and improved in [v5.0.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.0.0), so you can now get a reference to the actual `Throwable` via `event.originalError` in an `OnError` callback:
https://docs.bugsnag.com/platforms/android/customizing-error-reports/#errors

**Comment by M66B** [comment]
Thanks for actively letting me know @mattdyoung 
I will try to update soon.

**Comment by mattdyoung** [comment]
Please note that we've made a number of improvements to the interface for v5.0.0, some of which are breaking changes so please refer to the upgrade guide:
https://github.com/bugsnag/bugsnag-android/blob/v5.0.0/UPGRADING.md

**Comment by M66B** [comment]
I was already aware of that, but thanks @mattdyoung. If you like, I can report about my migration experience. I will attempt that likely next week.

**Comment by M66B** [comment]
I can't upgrade because this issue is not solved and the workaround for it cannot be used anymore:

https://github.com/bugsnag/bugsnag-android/issues/533

If you are interested in my upgrade experience, please see this patch (untested):

https://github.com/M66B/FairEmail/commit/b8ca986e2f2cf2c646dcb6c841b0b18ab0798236

I have one question: does resumeSession/pauseSession start/stop sending events to the Bugsnag server? If not, what is the right way to dynamically enable/disable reporting (privacy!).

Suggestion: add *Bugsnag.leaveBreadcrumb* with *Map<String, String>* as parameter too. In my case all Bugsnag logic is at one place, but that might not always be the case, causing extra work to upgrade leaveBreadcrumb calls.

**Comment by mattdyoung** [comment]
Hi @M66B 

The https://github.com/bugsnag/bugsnag-android/issues/533 is solved, which has been discussed separately under that issue.

Re this question:
>I have one question: does resumeSession/pauseSession start/stop sending events to the Bugsnag server? If not, what is the right way to dynamically enable/disable reporting (privacy!).

The client sends both sessions and events to Bugsnag. Event are the error reports whereas sessions are just used in conjunction with events to calculate what proportion of sessions resulted in an unhandled exception (the stability score).

When initializing the `Bugsnag` client, you can disable auto-capture of sessions:
https://docs.bugsnag.com/platforms/javascript/configuration-options/#autotracksessions
and disable auto-capture of errors:
https://docs.bugsnag.com/platforms/javascript/configuration-options/#autodetecterrors

If you wanted to dynamically stop sending data to Bugsnag after initialization, this can be done by using conditional logic in the `onSession` and `onError` callbacks to return `false` which would prevent the session or event from being sent:
https://docs.bugsnag.com/platforms/javascript/configuration-options/#autodetecterrors
https://docs.bugsnag.com/platforms/javascript/configuration-options/#onerror

Thanks for all the feedback!

**Comment by M66B** [comment]
@mattdyoung it has been done, thanks for the help!

**Comment by M66B** [comment]
@mattdyoung everything seems to work as expected!
