### ISSUE TITLE
Contributing guidelines URL in Android reference is incorrect

### ISSUE THREAD

**Issue by hzsweers** [bugsnag/bugsnag-android#59]
Not really sure where to post this, but just wanted to let you guys know.

The contributing guidelines link on the [android reference](https://bugsnag.com/docs/notifiers/android) page (at the bottom) points to [this](https://bugsnag.com/docs/api/CONTRIBUTING) dead URL.

Should it be pointing to [this](https://github.com/bugsnag/bugsnag-android/blob/master/CONTRIBUTING.md) instead?

**Comment by ConradIrwin** [comment]
Thanks!

Conrad
