### ISSUE TITLE
Add custom Delivery to exsisting Bugsnag Client

### ISSUE THREAD

**Issue by anilmaddala** [bugsnag/bugsnag-android#614]
How can I add a custom `Delivery` to a running Bugsnag instance.

The only API I found is making the delivery as part of the config and passing the config to init call.

If there is no API to add a `Delivery`, can we make the Bugsnag exsisting client `null` and restart bugsnag with a new `init`? what is the API

**Comment by mattdyoung** [comment]
Hi @anilmaddala 

Could you explain a little more about your use case for wanting a custom `Delivery`? It's an interface we're considering removing so we'd like to understand your usage to advise on the best way forward.

Thanks!

**Comment by anilmaddala** [comment]
Hi @mattdyoung 
I am specifically working with a proxy wifi network (with username and password). On Android I need to pass a custom Http client (like okhttp) which has my network details, to network dependent libraries (like Glide, Retrofit etc.) On Bugsnag, I am currently using a custom `Delivery` to configure okhttp with my network proxy details. Hope this helps explain my usecase.

**Comment by abigail-bugsnag** [comment]
Hi @anilmaddala - thank you for the additional information. Can you please tell us why you need to add a custom `Delivery` to an instance which is already running?

**Comment by anilmaddala** [comment]
@abigail-bugsnag I am essentially trying to add proxy network settings to Bugsnag, but the Bugsnag.init has already been called. So I either have to totally stop the current Bugsnag instance and restart it with proxy deails, or add the proxy details to current Bugsnag instance.

**Comment by mattdyoung** [comment]
Hi @anilmaddala 

So if I understand correctly the proxy settings aren't available at the point of `Bugsnag.init()`, so as well as the issue of reconfiguring the Bugsnag client to use a custom `Delivery` object, there's potentially an issue with error reports before this point being sent with the incorrect network settings.

What we'd suggest is: 
1. Construct the custom `Delivery` class and use this in the configuration for `Bugsnag.init()` even though the proxy settings aren't yet known. In your custom `Delivery` class, if the proxy settings aren't yet available, throw a `DeliveryFailureException` to tell Bugsnag to cache and retry sending the error report later.
2. When the proxy settings are available, update your `Delivery` subclass instance with the new settings, and deliver reports normally.
