### ISSUE TITLE
The permission.GET_TASKS" is deprecated.

### ISSUE THREAD

**Issue by Grozny** [bugsnag/bugsnag-android#62]
The permission.GET_TASKS" was deprecated in API level 21.
How can i use bugsnag android in Lollipop?

**Comment by jessicard** [comment]
Hey @Grozny - is GET_TASKS throwing an error for you? GET_TASKS is deprecated in level 21, but I think it's just that it's no longer enforced, so Bugsnag should still work.

**Comment by snmaynard** [comment]
Hey @Grozny - reopen this  if there is still an issue here!
