### ISSUE TITLE
Bugsnag drops a lot of crashes

### ISSUE THREAD

**Issue by pyricau** [bugsnag/bugsnag-android#63]
Here: https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/Client.java#L517

The crashes are written to disk asynchronously, and then the exception is handled to the default exception handler. 

If the app is in the foreground, the default handler will show the crash dialog and block there, then when the user clicks on it the default handler kills the process. See here: https://github.com/android/platform_frameworks_base/blob/master/core/java/com/android/internal/os/RuntimeInit.java#L88

If the app is in the background, there is no dialog, so the process dies immediately.

So this basically means that the process can die before the async work is done, so before the crash is saved to the file system.

We can't even work around that and use our own exception  handler, because we do not have any hook into the async work to wait for its completion.

Btw, `Async` uses `AsyncTask`. That's terrible, its internal behavior  has changed over Android versions. Don't use that.

**Comment by inetfuture** [comment]
Is this fixed? What's the current behavior?

I'm trying this library, but it doesn't report crash to dashboard. https://github.com/SudoPlz/react-native-bugsnag/issues/17#issuecomment-248900951

**Comment by inetfuture** [comment]
on this first device(Huawei Honor), it didn't show "Unfortunately, * has stopped" dialog, no reports at all.

I changed to another device, nexus, it shows the dialog, and if I wait on this dialog over ten seconds, the report will appear on dashboard, but if I click ok in less than ten seconds, nothing shows in dashboard.
