### ISSUE TITLE
Program type already present: com.bugsnag.android.BuildConfig

### ISSUE THREAD

**Issue by AlienAsRoger** [bugsnag/bugsnag-android#635]
### Expected behavior
Build Compilation should be sucessfull

### Observed behavior
Getting Error:
```
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.bugsnag.android.BuildConfig
```
### Steps to reproduce
In my code I have declared only in one module. Other modules doesn't have this declaration
```
    implementation 'com.bugsnag:bugsnag-android:4.21.1'
    implementation 'com.bugsnag:bugsnag-android-ndk:4.21.1'
```

1. Update bugsnag version from 4.11.0 -> 4.21.1
2. Compile and run project 

### Version
4.21.1

### Additional information
I tried with old bugsnag gradle plugin and with new one
`        classpath 'com.bugsnag:bugsnag-android-gradle-plugin:4.7.2'`

**Comment by AlienAsRoger** [comment]
Looks like solution was to remove `implementation 'com.bugsnag:bugsnag-android-ndk:4.11.0'`
since after 4.17 when packages were modularized

**Comment by mattdyoung** [comment]
Hi @AlienAsRoger 

Yes, that's right.

You should only need to have `implementation 'com.bugsnag:bugsnag-android:4.+'`:
https://docs.bugsnag.com/platforms/android/#installation

You can enable / disable reporting of NDK errors by adding this to your `AndroidManifest.xml`:
```
<meta-data android:name="com.bugsnag.android.DETECT_NDK_CRASHES"
             android:value="true"/>
```
https://docs.bugsnag.com/platforms/android/#reporting-ndk-errors
