### ISSUE TITLE
User class isn't public

### ISSUE THREAD

**Issue by jgreen210** [bugsnag/bugsnag-android#671]
### Expected behavior

client.getUser() and error.getUser() (in e.g. beforeNotify callback) are useful.

### Observed behavior

You can call the getUser() methods, but the returned User object is not public, so you can't use it.

### Steps to reproduce

N/A

### Version

4.21.1

### Additional information

Probably can't or shouldn't just make the User class public to fix this - it's got public setter methods on it, and don't want to allow internal state to be affected via these setters. Could make it read only, via an interface or something, if you can do that in a API compatible way. Alternatively, could make getUser() return a copy.

Why do I care? I want to write a beforeNotify handler that uses the current user to set other attributes in the Error. As a workaround, I can instead update the beforeNotify Handler when change the current user.

**Comment by mattdyoung** [comment]
Hi @jgreen210 

We already have changes to this interface we're working on which will make `User` public and read-only and just have a method on the client / error report to set the user.

This will be in the next major version of the library but there are a number of other changes being worked on for that version so it will still be a while until this is available.

Thanks!
