### ISSUE TITLE
Add logcat in errors

### ISSUE THREAD

**Issue by aschelch** [bugsnag/bugsnag-android#74]
Is it possible to add Logcat when a exception occurred ?

**Comment by JakeWharton** [comment]
No. Android does not provide access.

**Comment by aschelch** [comment]
Even using READ_LOGS permissions, or using Timber ?

**Comment by JakeWharton** [comment]
Read logs doesn't work on KitKat and up. And of course if you're not using
logcat you can add logs (e.g., with Timber) but the question was originally
for logcat.

**Comment by aschelch** [comment]
Ok, thanks for your answer. 

I just found how you did in Telecine app ;)

https://github.com/JakeWharton/Telecine/blob/master/telecine/src/main/java/com/jakewharton/telecine/BugsnagTree.java
https://github.com/JakeWharton/Telecine/blob/feee44b2cc3694161d10c98517f983b78aed3d6f/telecine/src/main/java/com/jakewharton/telecine/TelecineApplication.java

Nice job with Timber, Butterknife, Telecine and all the other stuff you do btw ;) :+1:
