### ISSUE TITLE
Original exception is lost for handled exceptions

### ISSUE THREAD

**Issue by hannesstruss** [bugsnag/bugsnag-android#746]
### Expected behavior

When registering a `beforeNotify` callback and reporting an exception via `Client.notify(Throwable, Severity)`, I would expect the original exception to be available in the `Error` instance passed to the callback.

### Observed behavior

`getException()` of the `Error` passed to the `beforeNotify` callback returns an instance of `BugsnagException`. `getCause()` of the `BugsnagException` returns the _cause_ of the error reported via `notify`, not the error itself.

### Steps to reproduce

1. Register a `beforeNotify` callback on your `Client`
2. Report an exception via `client.notify(exception, Severity.WARNING)`
3. Inspect `error.getException()` passed to the `beforeNotify` callback

### Version

4.22.2

### Additional information

This happens, because the reported exception gets passed to `BugsnagException`, and `BugsnagException` extracts the cause of the original exception and sets it as its own cause: https://github.com/bugsnag/bugsnag-android/blob/master/bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagException.java#L53

I would expect that either `BugsnagException` just sets the original exception itself as its cause, not the original exception's cause – even better would be though to not create a `BugsnagException` at all in the first place if there is an original exception available.

**Comment by M66B** [comment]
Duplicate of #577

**Comment by hannesstruss** [comment]
@M66B Thanks! I'll close this in favor of #577.

**Comment by M66B** [comment]
Did you notice that #577 was closed unsolved?

**Comment by hannesstruss** [comment]
Yeah, but as the maintainers are aware and working on a solution, I hope this'll get fixed. The same scenarios are breaking for me as they are for you.
