### ISSUE TITLE
Stuck at uploadBugsnagDebugMapping

### ISSUE THREAD

**Issue by ppamorim** [bugsnag/bugsnag-android#76]
This problem makes the compile impossible! Please create another way to update the map to bugsnag.

```
:app:uploadBugsnagDebugMapping
```

That`s all.

**Comment by snmaynard** [comment]
I don't really understand what you mean by this. I'm assuming this is related to our [gradle plugin](bugsnag/bugsnag-android-gradle-plugin), but in what way is it making your compile impossible? If you have more information I would recommend raising an issue on our [gradle plugin](bugsnag/bugsnag-android-gradle-plugin).
