### ISSUE TITLE
Response code 200 should be checked against HTTP_OK

### ISSUE THREAD

**Issue by georgiev-martin** [bugsnag/bugsnag-android#81]
At https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/HttpClient.java#L46, why use ad-hoc comparison and not compare against http://download.java.net/jdk7/archive/b123/docs/api/java/net/HttpURLConnection.html#HTTP_OK?

**Comment by kattrali** [comment]
Thanks for the report, @georgiev-martin. Did you encounter a particular bug with this? It looks like the check also allows for other status codes to be parsed successfully, such as 201 or 202, and not just 200. These could be checked individually, but the current handling seems sufficient for now.

**Comment by georgiev-martin** [comment]
All HTTP response codes have static constants, e.g., HTTP_OK, HTTP_CREATED, HTTP_ACCEPTED, etc. Comparing against them is the preferred way. It improves code quality, readability, extensibility, etc. Tests are also much easier to write and the functionality of the library/workflow tested. 

If your server returns response codes in the 2XX range, other than HTTP_OK (200), I would advise you to check against them here and also write appropriate tests to ensure that future SDK/server changes do not break any functionality.

Comparisons like this: https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/HttpClient.java#L46 would certainly not pass a code review at a large tech company. Let's strive for excellence!

**Comment by kattrali** [comment]
Ah, I see what you mean. It may be in the interest of stability to revisit this in the future.
