### ISSUE TITLE
Use HttpsURLConnection instead of HttpURLConnection

### ISSUE THREAD

**Issue by georgiev-martin** [bugsnag/bugsnag-android#82]
At https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/HttpClient.java#L28 and elsewhere use HttpsURLConnection. This promotes safe practices, since if the developer sets an HTTP URL, they will get an error similar to this one: "sun.net.www.protocol.http.HttpURLConnection cannot be cast to javax.net.ssl.HttpsURLConnection".

**Comment by snmaynard** [comment]
Unfortunately some of our customers dont use a https endpoint for their crashes, and we dont want to force them to do so. This is true when people are using it in internal networks and various other things. The default is https and I think that is all we need to do here.

Thanks for the idea though!
