### ISSUE TITLE
User object is package private, so can't access id.

### ISSUE THREAD

**Issue by peterdk** [bugsnag/bugsnag-android#856]
### Expected behavior
Bugsnag.client.user.id returns the bugsnag user ID.

### Observed behavior
User class is package private, not public. So while you can get the User object from Client. You can't access is it in your own code.

### Version
4.22.2

### Additional information
I want to log the bugsnag user id to our email template for users to report issues. We want cross account visibility of issues, so we prefer to use Bugsnag's generated ID so we can see users logging in and out when having issues. Although the getUser() method is public, the User object's properties like id, name and email, are not accessible from outside the bugsnag package. A workaround for us now is to create a class that's inside the package namespace, and returns us the id. But I prefer that it's just publicly available. It looks like a 'bug' not a intentional limitation, since getUser() is public.

**Comment by mattdyoung** [comment]
Hi @peterdk 

We're currently working on the next major release of bugsnag-android which will include an interface to retrieve the Bugsnag generated user ID from the client object.

**Comment by peterdk** [comment]
@mattdyoung Ok, great!

**Comment by johnkiely1** [comment]
This has now been fixed in [V5.0.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.0.0)
