### ISSUE TITLE
DeviceData default values.

### ISSUE THREAD

**Issue by d4rken** [bugsnag/bugsnag-android#86]
Example: https://github.com/bugsnag/bugsnag-android/blob/9470323e8e9eababd5dcc04d16a229f429e784e7/src/main/java/com/bugsnag/android/DeviceData.java#L72

If we can't obtain a value, is it not better to omit the value than to send a default value of "0"?
For someone checking stats in the webconsole, it would be better to see that the value isn't available instead of guessing whether bugsnag defaulted to that value or the system provided that value.

If this doesn't conflict with some API requirements of bugsnag, i would submit a pull request to change this.

**Comment by kattrali** [comment]
I agree, @d4rken, that not sending an invalid value is best, though I'd have to double-check the API requirements. It sounds like a good plan to exclude the device data values which are empty (zero value or zero-length string). I'd propose checking for empty values before they are written in `toStream` as a possible solution. 

/cc @snmaynard

**Comment by snmaynard** [comment]
The api has no requirements on this, so we should be able to make any required changes here. Seems like a good idea to me!

**Comment by d4rken** [comment]
About this:
https://github.com/bugsnag/bugsnag-android/blob/97eca13c7aa604a6578a231abb83cdfa5e14bf49/src/main/java/com/bugsnag/android/JsonStream.java#L29
So if we write a null value into the json stream, what does the API do?
Does it output "null" for the value in the webinterface or does it omit the value?

**Comment by d4rken** [comment]
@snmaynard Need some clarification on the API behavior ^

**Comment by kattrali** [comment]
Even if the API properly discarded null values, it is a bit inefficient to send data to be discarded, just as sending zeroes is in the current behavior. Checking whether to send those values and only sending them if the values are non-null before writing them would resolve this.

**Comment by kattrali** [comment]
Closed via #96, released in 3.3.0
