### ISSUE TITLE
UnsatisfiedLinkError from Bugsnag.init

### ISSUE THREAD

**Issue by stoyicker** [bugsnag/bugsnag-android#863]
### Expected behavior
No exception.

### Observed behavior
Exception.

### Version
4.22.3. I don't have occurrences of this in other versions but I cannot tell for sure that it was introduced there.

### Additional information
All occurrences on a Pixel 3 XL with Android 10.

#### Stacktrace
```
Google Pixel 3 XL (crosshatch), 3584MB RAM, Android 10

java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1067)
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1007)
  at java.lang.System.loadLibrary (System.java:1667)
  at com.bugsnag.android.NdkPlugin.<clinit> (NdkPlugin.java:9)
  at java.lang.Class.classForName (Class.java)
  at java.lang.Class.forName (Class.java:454)
  at java.lang.Class.forName (Class.java:379)
  at com.bugsnag.android.Client.<init> (Client.java:240)
  at com.bugsnag.android.Bugsnag.init (Bugsnag.java:77)
  at com.bugsnag.android.Bugsnag.init (Bugsnag.java:64)
  at com.bugsnag.android.Bugsnag.init (Bugsnag.java:37)
  at reporter.CrashReporterImpl$Bugsnag.init (CrashReporterImpl.java:14)
  ... continues in my code, the init call is from a ContentProvider I have and uses the Context returned by getContext()...
```

So far I only have two users whose device is showing this, so it might be that they are using some custom ROM that is missing the library you're trying to load, which I'd understand would arguably not be a problem on your side. But I'm not sure about that and, since I'm not using the ndk in my app, maybe the larger issue to discuss here is whether this NdkPlugin should be "activated" at all in such cases.

**Comment by phillipsam** [comment]
Hi @stoyicker thanks for the report. Can you please confirm how you are currently configuring Bugsnag? are you configuring in your AndroidManifest? or are you creating a configuration object via Java?

**Comment by stoyicker** [comment]
Through java, both in my Application class and in a ContentProvider. I know it is recommended to have it only the Application class but since the ContentProvider can (and, more often than not, is) be 'initialized' before the Application class, this proves problematic to report issues in the onCreate of the ContentProvider.

**Comment by phillipsam** [comment]
@stoyicker in the current notifier version, the config object set up in code will override any config set up in your AndroidManifest. Either way, even if the ndk module is disabled, it will still attempt to load. This is something that we are fixing in the next major release of bugsnag-android. In the meantime, you can exclude bugsnag-plugin-android-ndk from gradle if you do not require NDK error reporting.

**Comment by stoyicker** [comment]
I'm assuming I should also exclude the busnag-android-ndk module from com.bugsnag:bugsnag-android?

**Comment by mattdyoung** [comment]
@stoyicker 
Provided you're only depending on the bugsnag-android module, not the bugsnag-android-ndk module you should only need to exclude bugsnag-plugin-android-ndk, which you can do like this:
```
implementation("com.bugsnag:bugsnag-android:$version") {
    exclude group: "com.bugsnag", module: "bugsnag-plugin-android-ndk" // remove the NDK artefact, use the ANR + core
}
```

The bugsnag-android-ndk module is no longer required and is only provided for legacy reasons as it was previously a separate module which customers may still have dependencies on.

**Comment by stoyicker** [comment]
Oh I see, sorry, I thought @phillipsam meant that I should exclude it from com.bugsnag:bugsnag-android-gradle-plugin. My bad!
