### ISSUE TITLE
ANR reports are illogically grouped

### ISSUE THREAD

**Issue by peterdk** [bugsnag/bugsnag-android#886]
### Expected behavior
ANR's are grouped by callstack, not only the activity

### Observed behavior
I have 1700 ANR reports with each totally different causes grouped as 1 error

### Version
5.0.0

### Additional information
I don't see any logic in this grouping. And with 1700 errors, I am a bit lost on which cause of ANRs is really important, or are related to ad framework etc which I can't control.

**Comment by phillipsam** [comment]
Hi @peterdk - Our default grouping for errors is by top in-project stackframe:
https://docs.bugsnag.com/product/error-grouping/#top-in-project-stackframe

If you wish to group these errors differently, you can create a custom [groupingHash](https://docs.bugsnag.com/platforms/android/customizing-error-reports/#groupinghash) within a [callback](https://docs.bugsnag.com/platforms/android/customizing-error-reports/#updating-events-using-callbacks).

In a callback, you could also [prevent sending](https://docs.bugsnag.com/platforms/android/customizing-error-reports/#discarding-events) ANRs if they are related to ad framework which you can't control and therefore may not wish to see these particular ANRs reported to your dashboard.
