### ISSUE TITLE
Make Client#getBreadcrumbs public

### ISSUE THREAD

**Issue by pyricau** [bugsnag/bugsnag-android#892]
Currently Client#getBreadcrumbs is package private, yet Breadcrumb is public. I'm trying to switch us over from our own internal breadcrumb logs to Bugsnag's breadcrumbs, but I also need to be able to get the full list of breadcrumbs at any point to send it somewhere else ideally I would rely on a single store instead of storing those our own ring buffer + Bugsnag's ring buffer.

**Comment by xander-jones** [comment]
Hey @pyricau, thanks for the suggestion. I've passed this on to the Android notifier team to check out. We can't see any reason at the moment why this should not be made possible, so we'll take a look into this.

In the meantime, whilst this would go against your requirement to store in two separate buffers; the breadcrumbs can be exposed using an `OnBreadcrumbCallback` method: https://docs.bugsnag.com/platforms/android/configuration-options/#addonbreadcrumb

**Comment by pyricau** [comment]
Thanks @xander-jones ! I know about `OnBreadcrumbCallback`, and we don't even need this as all breadcrumbs go through an internal facade layer so we could store them there in a separate buffer but I'd rather avoid using twice the memory if I can.

**Comment by mattdyoung** [comment]
@pyricau 
This is now released in [v5.1.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.1.0).

**Comment by pyricau** [comment]
🙏 thanks!
