### ISSUE TITLE
Distribute the library only as aar (not as jar)

### ISSUE THREAD

**Issue by larsgrefer** [bugsnag/bugsnag-android#90]
Using an aar instead of a simple jar has two advantages:
- An aar can declare `<uses-permission />`-elements in its own manifest which gets merged to the apps manifest during the build.
- An aar can contain proguard rules which are used during the build of the app.
  - http://google.github.io/android-gradle-dsl/1.5/com.android.build.gradle.internal.dsl.ProductFlavor.html#com.android.build.gradle.internal.dsl.ProductFlavor:consumerProguardFiles

**Comment by kattrali** [comment]
That makes a lot of sense, @larsgrefer, thanks. I'll take a look. Any thoughts, @snmaynard?

**Comment by larsgrefer** [comment]
I can provide a PR for that if you like

**Comment by kattrali** [comment]
That would be awesome!

**Comment by larsgrefer** [comment]
By the way: This will solve #50 too

**Comment by larsgrefer** [comment]
@kattrali @JakeWharton @snmaynard When we let the library ship its own proguard rules we should answer the following question too:
>Is there a reason you run proguard on the library at all?

Source: https://github.com/bugsnag/bugsnag-android/issues/39#issuecomment-74978601

**Comment by SecUpwN** [comment]
@bugsnag, would you please pay special attention to this Issue? We would like it to be solved soon, otherwise we cannot implement https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/714. Thanks!
