### ISSUE TITLE
[Device data]Free disk amount swapped with free memory

### ISSUE THREAD

**Issue by pbajurko** [bugsnag/bugsnag-android#903]
### Expected behavior
_Free memory_ field represents remaining memory that app can allocate in VM. 

### Observed behavior
<img width="284" alt="Zrzut ekranu 2020-07-17 o 07 36 59" src="https://user-images.githubusercontent.com/65332883/87752606-06090b80-c801-11ea-94ab-0eb86a2011f7.png">

### Steps to reproduce
Produce bugsnag event on android device.

### Version
5.0.0

### Additional information
To fix swap lines [here](https://github.com/bugsnag/bugsnag-android/blob/master/bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt#L53)

**Comment by johnkiely1** [comment]
Hi @pbajurko 

Great spot on this, we will get this corrected ASAP.

Thanks
