### ISSUE TITLE
Document that app.packageName was removed from 5.0

### ISSUE THREAD

**Issue by pyricau** [bugsnag/bugsnag-android#907]
After upgrading to 5.0 and releasing, we noticed that the index we had on `app.packageName` was coming up empty.

Turns out this changed in 5.0, in [this PR](https://github.com/bugsnag/bugsnag-android/pull/732) :

> Removed `packageName` from the `app` metadata tab, as the field is duplicated by `app.id`

Would be nice to add that to the changelog, it was quite a surprise for us (I reindexed on `app.id` so should be all good now)

**Comment by steve-nester-uk** [comment]
Thanks for raising @pyricau, we're going to retrospectively update the UPGRADING.md notes (referenced in the changelog).
