### ISSUE TITLE
ANRs being missed on some devices

### ISSUE THREAD

**Issue by RicoYao** [bugsnag/bugsnag-android#923]
### Expected behavior
In the BugSnag sample Android app, triggering an ANR should bring up the ANR dialog and report an ANR every time.

### Observed behavior
On some devices such as a OnePlus 7t, the ANR dialog and corresponding report is only generated about half the time. On a Pixel 2XL it works almost 100% of the time.

### Steps to reproduce
Click on the "TRIGGER AN ANR" button (and then try to do more screen touches) in the BugSnag sample Android App on a OnePlus 7t. Repeat multiple times. Notice that the ANR dialog only shows up about half the time.

### Version
- 5.0.0 in sample app
- 4.22.3 in my own app

### Additional information
On Google Play Console, I noticed that ANR volume for my app dropped by 50% when I enabled BugSnag's ANR detector. So BugSnag was actually preventing Google from reporting it.

**Comment by johnkiely1** [comment]
Hi @RicoYao, 

Thanks for this, we have had some other reports of this and are currently investigating. We will update you as soon as know more.

**Comment by RicoYao** [comment]
Any chance there's any new information to report? Thanks.

**Comment by shashachu** [comment]
Looks like should be fixed with https://github.com/bugsnag/bugsnag-android/pull/1078

**Comment by phillipsam** [comment]
@shashachu you are correct! Yes, there is a fix for this in [v5.5.1](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.5.1). Do let us know if you have any further issues.
