### ISSUE TITLE
Breadcrumb metadata truncated in case of NDK crash

### ISSUE THREAD

**Issue by tann36** [bugsnag/bugsnag-android#926]
When an NDK crash happens on android, breadcrumb metadata strings are truncated to 64 characters on the web-app. If an error happens in java, the very same breadcrumb metadata is shown in its entirety. 

To be clear, I'm talking about a single value in the map of key-value pairs. I have not found this limit be described in the documentation.

Bugsnag version is 5.0.2

**Comment by mattdyoung** [comment]
Hi @tann36 

Yes, this is the current behavior as for NDK crashes the memory used to store these metadata values is statically allocated:
https://github.com/bugsnag/bugsnag-android/blob/4eed5a5a73fe6b13f4a1b7fc8d417e7d648ffaf1/bugsnag-plugin-android-ndk/src/main/jni/event.h#L112-L141

We're looking to improve this in the future as for elements of the error report such as breadcrumbs which are stored before crash time it is safe to allocate the memory dynamically.

**Comment by luke-belton** [comment]
Hi @tann36 - just letting you know that we've released [v5.24.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.24.0) of bugsnag-android, which includes some enhancements to metadata reporting on NDK crashes, including not truncating metadata strings at 63 characters 🎉
