### ISSUE TITLE
Event reports from phones in arabic / farsi locales report screenResolution in arabic numbers

### ISSUE THREAD

**Issue by RobBlairInq** [bugsnag/bugsnag-android#99]
From the device tab of the event log, 

locale | ar_AE
...
screenResolution |  ١٢٨٠x٨٠٠

Similar for other locales, including fa_IR

https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/DeviceData.java#L104 should probably specify Locale.US for standardization.

Might be tricky to unit test

**Comment by RobBlairInq** [comment]
![screen shot 2016-02-17 at 3 31 52 pm](https://cloud.githubusercontent.com/assets/1329154/13129968/957ead50-d595-11e5-98bb-768ba50b6646.png)

**Comment by kattrali** [comment]
Thanks for the report, @RobBlairInq. Nice catch! That and a few other places should definitely be using `Locale` before printing. Investigating.

**Comment by RobBlairInq** [comment]
Thanks!

**Comment by kattrali** [comment]
No problem! Thanks for reporting it. :tada:
