### ISSUE TITLE
Merged Manifest includes formatting and comments

### ISSUE THREAD

**Issue by AdamMTGreenberg** [bugsnag/bugsnag-android#991]
### Describe the bug
After upgrading to 5.+ the Android merged manifest on a multi-multi module project includes all of the formatting and comments from the `AndroidManifest.xml`s. They no longer align with the expected output. This is an issue since we can use the merged manifests to ensure no services, activities, listeners, or other errant permissions are added to the application via checks at build time in our CI. 

### Steps to reproduce
1. Run a typical `./gradle assemble`
2. Open the manifest found in the `project_root/build/intermediates/merged_manifests/../AndroidManifest.xml`
3. Note that all comments from other manifests and XML formatting still exist in the manifest. Prior to upgrade the formatting and comments did not propagate forward.

### Environment
* Android version: All
* Bugsnag version: 5.+
* Emulator or physical device: n/a

### Actual output:

```
 <provider
              android:name="leakcanary.internal.LeakSentryInstaller"
              android:authorities="com.pinterest.ota.leak-sentry-installer"
              android:exported="false" /> <!-- The activities will be merged into the manifest of the hosting app. -->
          <activity
              android:name="com.google.android.play.core.missingsplits.PlayCoreMissingSplitsActivity"
              android:enabled="false"
              android:exported="false"
              android:launchMode="singleInstance"
              android:process=":playcore_missing_splits_activity"
              android:stateNotNeeded="true" />
          <activity
              android:name="com.google.android.play.core.common.PlayCoreDialogWrapperActivity"
              android:enabled="false"
              android:exported="false"
              android:stateNotNeeded="true"
              android:theme="@style/Theme.PlayCore.Transparent" /> <!-- The service will be merged into the manifest of the hosting app. -->
          <service
              android:name="com.google.android.play.core.assetpacks.AssetPackExtractionService"
              android:enabled="false"
              android:exported="true" />
```

### Expected output:

```
<provider android:name="leakcanary.internal.LeakSentryInstaller" android:authorities="com.pinterest.ota.leak-sentry-installer" android:exported="false"/>
      <activity android:name="com.google.android.play.core.missingsplits.PlayCoreMissingSplitsActivity" android:enabled="false" android:exported="false" android:launchMode="singleInstance" android:process=":playcore_missing_splits_activity" android:stateNotNeeded="true"/>
      <activity android:name="com.google.android.play.core.common.PlayCoreDialogWrapperActivity" android:enabled="false" android:exported="false" android:stateNotNeeded="true" android:theme="@style/Theme.PlayCore.Transparent"/>
      <service android:name="com.google.android.play.core.assetpacks.AssetPackExtractionService" android:enabled="false" android:exported="true"/>
```

**Comment by mattdyoung** [comment]
Hi @AdamMTGreenberg 

What version of Android Gradle Plugin are you using? And what version were you using prior to upgrading bugsnag-android-gradle-plugin from v4.x to v5.x?

We added support for AGP 4.1 in bugsnag-android-gradle-plugin v5.x and the new AGP version uses a different mechanism for writing the manifest, so it would be good to understand if the change of behaviour is due to Bugsnag or AGP.

**Comment by mattdyoung** [comment]
Closing due to no response, but happy to re-open if further information comes to light.

**Comment by AdamMTGreenberg** [comment]
@mattdyoung apologies for the delay, I wasn't alerted to the response on this thread for some reason. We are currently using the Bugsnag gradle plugin 5.3.0

**Comment by johnkiely1** [comment]
Hi @AdamMTGreenberg, 

Thanks for this, I have tried reproducing this but have found that running `gradle assemble` on an application seems to retain the comments and formatting as per the manifest. This happens on an application that doesn't contain the Bugsnag Gradle Plugin.  

Could you describe your project structure a little more? Where is the manifest, containing the above code in relation to the top level manifest?

Is it possible something else has changed in you manifest(s) files or structure such that now it is being merged differently into to the top level manifest and hence including the comments this time but was excluding them previously?

**Comment by AdamMTGreenberg** [comment]
@johnkiely1 

> Where is the manifest, containing the above code in relation to the top-level manifest?
For the example used, both `com.google.android.play.core.common.PlayCoreDialogWrapperActivity"` and `leakcanary.internal.LeakSentryInstaller` pieces come from extrenal libraries.

We do have examples where the comments remain (are not stripped from the merged manifest) in our own code - in a few of the cases, it would be our top-most module. Eg:

```
          App <---- here
             |
         Base
        /       \
 Model    Rules
```

> Is it possible something else has changed in you manifest(s) files or structure such that now it is being merged differently into to the top level manifest and hence including the comments this time but was excluding them previously?
As far as we know, nothing. When we toggle between the Bugsnag 5.+ upgrade and then downgrade it, the comments are stripped from the merged manifest as expected. Could it be potentially a way the plugin interacts with a 3rd party?

**Comment by johnkiely1** [comment]
@AdamMTGreenberg 

Thanks for that info. 

Could I confirm are you upgrading/downgrading the Bugsnag Gradle plugin (`com.bugsnag:bugsnag-android-gradle-plugin:5.+`) or the Bugsnag Android library (`com.bugsnag:bugsnag-android:5.+`) when you see this change in behaviour? 
Are you also changing Gradle or AGP versions at the same time? Which versions of these are you using?

It's possible that there is some unexpected behaviour with a third party causing this. I have tried a number of different combinations and in all cases am seeing the comments being propagated to the merged manifest, so I wonder if there is a subtlety I am missing.   

To continue the investigation it would be helpful to see exactly how you have things set up. 

During each of the builds there should be a `manifest-merger-<productFlavour>-report.txt` produced in the `build/outputs/logs` directory. It would be really interesting to see and compare the output from the builds both before and after the upgrade. Would you be willing to share these .txt files with us?

Also it would be useful to see any relevant `build.gradle` files to get an idea of the other dependencies involved here.

You can send those in to us at support@bugsnag.com if you don't want to share publicly. Feel free to redact anything sensitive. 
Thanks

**Comment by mattdyoung** [comment]
We haven't been able to reproduce this so leaving as closed for now, but do let us know if you're able to share more of the info we asked for above and we can re-open and investigate further.

**Comment by AdamMTGreenberg** [comment]
Ah, sorry, I missed this over the holiday break. 

To confirm, we are seeing this with "upgrading/downgrading the Bugsnag Gradle plugin (com.bugsnag:bugsnag-android-gradle-plugin:5.+)" alone

I think there might be some confusion, with regard to:
> in all cases am seeing the comments being propagated 

The behaviour we were seeing before is that the comments were being stripped out. After the upgrade, they persist.

I can follow up with an email this week.

Cheers.

**Comment by johnkiely1** [comment]
Hi Adam,
Just wanted to follow up on this, it now looks to me when running `.gradlew assemble` the debug variant has the comments included and the release variant has stripped them out. I did notice some interesting behaviour using AGP 4.1 where an additional merged_manifest folder is generated with a release version of the manifest containing the comments and one without.  

Just to rule a couple of things out, what versions of AGP and Android Studio are you using? Are you doing a full clean in between builds?
What does your `merged_manifests` directory structure look like, do you have that additional `merged_manifest` folder?
Were you able to get the `manifest-merger-<productFlavour>-report.txt` for your builds?

If you dont mind would you be able to send through any configuration you have for the Bugsnag gradle plugin in your `build.gradle `file?

Thanks
